### ISSUE TITLE
Error with Kafka Connect 0.11.0.0

### ISSUE THREAD

**Issue by dex4zero4zone4** [confluentinc/kafka-connect-storage-cloud#121]
We are upgrading Kafka Connect from Confluent version 3.2.2 to 3.3.0 and are facing an issue (see below) when trying to connect to an independently managed centralized Kafka cluster, which is version 0.10.2.1-cp2, during start up. The reason for the issue is that our Kafka Connect consumer is only authorized for read access to the Kafka cluster, but when we upgrade to version 3.3.0 it is also trying to do a write on the kafka cluster. This was not happening with version 3.2.2. Is there a way to stop Kafka Connect trying to do the write action during start up in version 3.3.0?

ERROR Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:206)
org.apache.kafka.connect.errors.ConnectException: Error while attempting to create/find topic(s) '<our offset topic>'
                at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:245)
                at org.apache.kafka.connect.storage.KafkaOffsetBackingStore$1.run(KafkaOffsetBackingStore.java:99)
                at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:126)
                at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.start(KafkaOffsetBackingStore.java:109)
                at org.apache.kafka.connect.runtime.Worker.start(Worker.java:146)
                at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:99)
                at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:194)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownServerException: User <our user account> is not authorized for OWNER for destination kafka-cluster
                at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
                at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
                at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
                at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:213)
                at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:226)
                ... 11 more

If this is the wrong place to post this issue, can you point me in the right direction. Kafka repo doesn't have an issues tab.

**Comment by kkonstantine** [comment]
Since that version, Kafka Connect (the framework) is attempting to create its three internal topics upon startup if they are not present. Please, create beforehand with desired permissions and appropriate configuration. If they are present, Connect will not attempt to create the topics and will finish startup correctly. 

Also, closing here, since this is a framework issue and not related to this specific connector.
