### ISSUE TITLE
Can't extract partition time from JSON

### ISSUE THREAD

**Issue by gwilym** [confluentinc/kafka-connect-storage-cloud#152]
When trying to partition files by a timestamp field I get the following exception. The `timestamp` field exists but seems that my settings for JSON are incompatible somehow with the date field extraction.

Can I fix this with configs? Or is this not supported?

```
[2018-03-22 01:53:33,224] ERROR WorkerSinkTask{id=gwilym-athena-s3-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: The nested field named 'timestamp' does not exist.
	at io.confluent.connect.storage.util.DataUtils.getNestedFieldValue(DataUtils.java:54)
	at io.confluent.connect.storage.partitioner.TimeBasedPartitioner$RecordFieldTimestampExtractor.extract(TimeBasedPartitioner.java:276)
	at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:199)
	at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:176)
	at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:195)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:524)
	... 10 more
Caused by: org.apache.kafka.connect.errors.DataException: Argument not a Struct or Map. Cannot get field 'timestamp' from: {referer={prompt=, url=}, request={ip=REDACTED, accept_language=, id=3e34f3a92b42db5474e6c9e35e0e55bb, url=REDACTED, user_agent=Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)}, event_id=store-3-dal9-15069057807, payload={REDACTED}, experiments={REDACTED}, initiator={visitor_id=REDACTED, session_id=REDACTED, id=, visit_id=REDACTED, type=ANONYMOUS, application_id=}, producer={agent=REDACTED, source=REDACTED, flow=}, event=REDACTED, version=2.0.0, timestamp=2018-03-21T06:40:43.29898400Z}
	at io.confluent.connect.storage.util.DataUtils.getField(DataUtils.java:37)
	at io.confluent.connect.storage.util.DataUtils.getNestedFieldValue(DataUtils.java:49)
	... 15 more
[2018-03-22 01:53:33,224] ERROR WorkerSinkTask{id=gwilym-athena-s3-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:173)
```

I am trying this using the latest master branch in a dev build.

My standalone config:

```
bootstrap.servers=kafka:9093
security.protocol=SSL
ssl.truststore.location=REDACTED
ssl.truststore.password=REDACTED
ssl.keystore.location=REDACTED
ssl.keystore.password=REDACTED
ssl.key.password=REDACTED

producer.security.protocol=SSL
producer.ssl.truststore.location=REDACTED
producer.ssl.truststore.password=REDACTED
producer.ssl.keystore.location=REDACTED
producer.ssl.keystore.password=REDACTED
producer.ssl.key.password=REDACTED

consumer.security.protocol=SSL
consumer.ssl.truststore.location=REDACTED
consumer.ssl.truststore.password=REDACTED
consumer.ssl.keystore.location=REDACTED
consumer.ssl.keystore.password=REDACTED
consumer.ssl.key.password=REDACTED

key.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false

value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

# The internal converter used for offsets and config data is configurable and must be specified, but most users will
# always want to use the built-in default. Offset and config data is never visible outside of Kafka Connect in this format.
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000

plugin.path=/opt/kafka-connect-storage-cloud/kafka-connect-s3/target/kafka-connect-s3-5.0.0-SNAPSHOT-package/share/java/
```

My task config:

```
name=gwilym-athena-s3
connector.class=io.confluent.connect.s3.S3SinkConnector
tasks.max=1

topics=REDACTED

format.class=io.confluent.connect.s3.format.json.JsonFormat
flush.size=1000
rotate.interval.ms=600000

s3.bucket.name=REDACTED
s3.region=REDACTED
s3.compression.type=gzip
s3.part.retries=10

storage.class=io.confluent.connect.s3.storage.S3Storage
topics.dir=/tmp/topics

partitioner.class=io.confluent.connect.storage.partitioner.TimeBasedPartitioner
timestamp.extractor=RecordField
timestamp.field=timestamp
locale=en-US
timezone=UTC
path.format='test/yr'=YYYY/'mo'=MM/'dy'=dd/'hr'=HH
partition.duration.ms=3600000
schema.compatibility=NONE
```

**Comment by gwilym** [comment]
@cricket007 since I'm not a Java expert I find the dependency ecosystem of kafka-connect difficult to grok. Would this fix be available to use now using released JAR versions? Thanks.

**Comment by cricket007** [comment]
Starting at Confluent 4.1.2, yes.

See https://github.com/confluentinc/kafka-connect-storage-common/commit/509292ba80babf84e4653e6b71e0947dc0532559

**Comment by kkonstantine** [comment]
`5.0.0` and `4.1.2` both have been released and contain the fix. Closing here.
