### ISSUE TITLE
Cannot start kafka-connect-s3 for develpment

### ISSUE THREAD

**Issue by nestorbolivar** [confluentinc/kafka-connect-storage-cloud#178]
```
bootstrap.servers=172.20.52.5:9091,172.20.52.69:9091
rest.port=8083
group.id=connect-cluster
config.storage.topic=connect-configs
offset.storage.topic=connect-offsets
status.storage.topic=connect-status
config.storage.replication.factor=2
offset.storage.replication.factor=2
status.storage.replication.factor=2
rest.advertised.host.name=localhost
log4j.root.loglevel=TRACE
log4j.loggers="org.reflections=TRACE"
ssl.keystore.location=/usr/local/kafka/config/keystore.jks
ssl.keystore.password=changeit
ssl.key.password=changeit
ssl.truststore.location=/usr/local/kafka/config/truststore.jks
ssl.truststore.password=changeit
ssl.protocol=TLS
truststore.type=JKS
keystore.type=JKS
ssl.secure.random.implementation=SHA1PRNG
ssl.keymanager.algorithm=SunX509
security.protocol=SSL
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
plugin.path=/usr/share/java/confluent-common,/usr/share/java/kafka-connect-storage-common,/usr/share/java/kafka-connect-s3
```

```
[2018-06-26 01:41:38,624] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/java/kafka-connect-s3/jmespath-java-1.11.86.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:199)
[2018-06-26 01:41:38,624] INFO Loading plugin from: /usr/share/java/kafka-connect-s3/kafka-connect-s3-4.1.1.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:176)
Exception in thread "main" java.lang.NoClassDefFoundError: io/confluent/connect/storage/StorageSinkConnectorConfig
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:54)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.getPluginDesc(DelegatingClassLoader.java:242)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:223)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:198)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:190)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:150)
        at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:47)
        at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:63)
Caused by: java.lang.ClassNotFoundException: io.confluent.connect.storage.StorageSinkConnectorConfig
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:62)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 22 more
tail: connectDistributed.out: file truncated
```

if I change 

```
plugin.path=/usr/share/java/confluent-common,/usr/share/java/kafka-connect-storage-common,/usr/share/java/kafka-connect-s3
```

to 

```
plugin.path=/usr/share/java/
```

```
[2018-06-26 01:43:58,836] ERROR Could not get listing for plugin path: /usr/share/java. Ignoring. (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:167)
java.nio.file.NoSuchFileException: ../kafka-connect-storage-common
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixPath.toRealPath(UnixPath.java:837)
        at org.apache.kafka.connect.runtime.isolation.PluginUtils.pluginUrls(PluginUtils.java:196)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:178)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:150)
        at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:47)
        at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:63)
```

These are the packages installed:

```
[root@dev1-kaf-node-1-5 logs]# rpm -qa|grep confluent
confluent-kafka-connect-storage-common-4.1.1-1.noarch
confluent-common-4.1.1-1.noarch
confluent-kafka-connect-s3-4.1.1-1.noarch
```

**Comment by nestorbolivar** [comment]
```
kafka_version: "0.11.0.2"
kafka_scala_version: "2.11"  #2.11 is recommended
```

**Comment by novskey** [comment]
The only way I could get it running was to set classpath like so: `/home/ubuntu/kafka-connect-storage-cloud/kafka-connect-s3/target/kafka-connect-s3-5.1.0-SNAPSHOT-package/share/java/kafka-connect-s3/*:/home/ubuntu/kafka-connect-storage-common/package-kafka-connect-storage-common/target/kafka-connect-storage-common-package-5.1.0-SNAPSHOT-package/share/java/kafka-connect-storage-common/*:/home/ubuntu/common/package/target/common-package-5.1.0-SNAPSHOT-package/share/java/confluent-common/*
`

I also had to remove `guava-14.0.1.jar` from `kafka-connect-storage-common/package-kafka-connect-storage-common/target/kafka-connect-storage-common-package-5.1.0-SNAPSHOT-package/share/java/kafka-connect-storage-common/`, but there must be an easier way.

**Comment by nestorbolivar** [comment]
Cheers @novskey,  I just made it work downloading the plugin from
 
```https://api.hub.confluent.io/api/plugins/confluentinc/kafka-connect-s3/versions/4.1.1/archive```

That's a zip file that, once decompressed, contains all the dependencies.

**Comment by nestorbolivar** [comment]
BTW, I'm running it on Centos7
