### ISSUE TITLE
I cannot make the S3 connector work - No 'ERROR|WARN' message in the log output

### ISSUE THREAD

**Issue by nestorbolivar** [confluentinc/kafka-connect-storage-cloud#180]
My configuration;

config/connect-distributed.properties
```
bootstrap.servers=XX.XX.XX.XX:9091,XX.XX.XX.XX:9091
rest.port=8083
group.id=kafka-connect-cluster
config.storage.topic=kafka-connect-configs
offset.storage.topic=kafka-connect-offsets
status.storage.topic=kafka-connect-status
config.storage.replication.factor=2
offset.storage.replication.factor=2
status.storage.replication.factor=2
rest.advertised.host.name=localhost
ssl.keystore.location=/usr/local/kafka/config/keystore.jks
ssl.keystore.password=super-secure-password
ssl.key.password=super-secure-password
ssl.truststore.location=/usr/local/kafka/config/truststore.jks
ssl.truststore.password=super-secure-password
ssl.protocol=TLS
truststore.type=JKS
keystore.type=JKS
ssl.secure.random.implementation=SHA1PRNG
ssl.keymanager.algorithm=SunX509
security.protocol=SSL
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
plugin.path=/usr/share/java/confluentinc-kafka-connect-s3-4.1.1
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
```

I create the connector like this:

```
curl -s -X POST -H "Content-Type: application/json" --data '
{
"name": "events-test",
"config": {
"connector.class": "io.confluent.connect.s3.S3SinkConnector",
"tasks.max": "3",
"topics": "events-test",
"s3.region": "ap-southeast-2",
"s3.bucket.name": "a-random-s3-bucket",
"s3.part.size": "5242880",
"flush.size": "100",
"storage.class": "io.confluent.connect.s3.storage.S3Storage",
"format.class": "io.confluent.connect.s3.format.json.JsonFormat",
"schema.generator.class": "io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator",
"partitioner.class": "io.confluent.connect.storage.partitioner.DefaultPartitioner",
"schema.compatibility": "NONE",
"rotate.schedule.interval.ms": "10000",
"timezone": "UTC",
"locale": "US",
"name": "events-test"
}
 }' http://127.0.0.1:8083/connectors
```

```
[2018-07-02 11:32:01,545] INFO Started S3 connector task with assigned partitions: [] (io.confluent.connect.s3.S3SinkTask:115)
[2018-07-02 11:32:01,545] INFO Sink task WorkerSinkTask{id=events-2} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:247)
[2018-07-02 11:32:01,611] INFO Started S3 connector task with assigned partitions: [] (io.confluent.connect.s3.S3SinkTask:115)
[2018-07-02 11:32:01,611] INFO Sink task WorkerSinkTask{id=events-test-1} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:247)
[2018-07-02 11:32:04,900] INFO Started S3 connector task with assigned partitions: [] (io.confluent.connect.s3.S3SinkTask:115)
[2018-07-02 11:32:04,900] INFO Sink task WorkerSinkTask{id=events-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:247)
```

Debug mode continues showing messages like these:

```[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-4 at offset 0 to node ip-172-20-52-5.ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.con
sumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-6 at offset 0 to node ip-172-20-52-5.ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.con
sumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-0 at offset 0 to node ip-172-20-52-5.ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.con
sumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-2 at offset 0 to node ip-172-20-52-5.ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.con
sumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-20 at offset 0 to node ip-172-20-52-5.ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.co
nsumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-22 at offset 0 to node ip-172-20-52-5.ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.co
nsumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-16 at offset 0 to node .ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.co
nsumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-18 at offset 0 to node .ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.co
nsumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-12 at offset 0 to node .ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.co
nsumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-14 at offset 0 to node .ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.co
nsumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-8 at offset 0 to node ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.con
sumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-10 at offset 0 to node ip-172-20-52-5.ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.co
nsumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Added READ_UNCOMMITTED fetch request for partition kafka-connect-offsets-24 at offset 0 to node .ap-southeast-2.compute.internal:9091 (id: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.co
nsumer.internals.Fetcher:787)
[2018-07-02 12:01:00,007] DEBUG Sending READ_UNCOMMITTED fetch for partitions [kafka-connect-offsets-4, kafka-connect-offsets-6, kafka-connect-offsets-0, kafka-connect-offsets-2, kafka-connect-offsets-20, kafka-connect-offsets-22, kafka-c
onnect-offsets-16, kafka-connect-offsets-18, kafka-connect-offsets-12, kafka-connect-offsets-14, kafka-connect-offsets-8, kafka-connect-offsets-10, kafka-connect-offsets-24] to broker ip-172-20-52-5.ap-southeast-2.compute.internal:9091 (i
d: 1 rack: ap-southeast-2a) (org.apache.kafka.clients.consumer.internals.Fetcher:201)
```

Please note the offsets always stay on 0 and it never increases.

I can see messages like this one:

```
[2018-07-02 12:01:00,043] DEBUG Connection with / disconnected (org.apache.kafka.common.network.Selector:401)
java.io.EOFException
        at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:103)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:75)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:203)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:167)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:381)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:326)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:433)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:232)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:208)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:199)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:134)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:226)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:203)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:286)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1078)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1043)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:382)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:260)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:150)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

But I understand that's related to keepalives.

```
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-4 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSizeI
nBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-6 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSizeI
nBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-0 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSizeI
nBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-2 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSizeI
nBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-20 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSize
InBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-22 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSize
InBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-16 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSize
InBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-18 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSize
InBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-12 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSize
InBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-14 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSize
InBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-8 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSizeI
nBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,006] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-10 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSize
InBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-07-02 12:01:00,007] DEBUG Fetch READ_UNCOMMITTED at offset 0 for partition kafka-connect-offsets-24 returned fetch data (error=NONE, highWaterMark=0, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSize
InBytes=0) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
```

**Comment by kkonstantine** [comment]
@nestorbolivar seems that the connector started but wasn't able to retrieve any records from Kafka. Were you able to resolve this? The connector works, so this might be a transient error of your deployment.

**Comment by kkonstantine** [comment]
Closing since I have no evidence this is still an issue. Feel free to reopen if this is not the case.

**Comment by etadelta222** [comment]
@kkonstantine , I've run across the same issue as above. We have SSL turned on and although the connector status is running, there are no error messages in the connect.log but and nothing is being written to S3. Used the instructions here (https://docs.confluent.io/current/kafka/authentication_ssl.html#kafka-connect) to update the connector properties and the connect-distributed.properties files as well. Please advise.

**Comment by tlazar** [comment]
I came across this issue and tracked it down to needing to set the consumer SSL properties as well (ex. `consumer.bootstrap.servers=kafka1:9093`).  See [here](https://docs.confluent.io/current/kafka/authentication_ssl.html).  It seems that without those additional properties, messages aren't even picked up by Kafka connect to handoff to this connector.  @etadelta222, @nestorbolivar

**Comment by Hubbitus** [comment]
I think it is totally incorrect - if connector can't work, why there silence in logs??

**Comment by jpelletier-dad** [comment]
Have the same issue. I agree, at the very least I'd expect to see errors without having to turn log level to DEBUG.

**Comment by zhangdi-devel** [comment]
Encountered the same problem. Solved by adding the conf for consumer and producer. See the[ example](https://github.com/confluentinc/cp-docker-images/blob/1d24bda21eac209b5716d53e8e627427052e961d/examples/cp-all-in-one-cloud/docker-compose.yml#L142-L157) of the docker image repo.

**Comment by anchavesbV** [comment]
This just happened to me, after hours debugging the only hint was this INFO msg:

Started S3 connector task with assigned partitions: []

Thanks for the example docker image.

**Comment by jpelletier-dad** [comment]
as a starting point, these are my S3 connector environment variables (i'm using the docker image here: https://hub.docker.com/r/confluentinc/cp-kafka-connect)
```
COMPONENT=kafka-connect
CONNECT_CONFIG_STORAGE_TOPIC=dev.connector.config
CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=3
CONNECT_STATUS_STORAGE_TOPIC=dev.connector.status
CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
CONNECT_OFFSET_STORAGE_TOPIC=dev.connector.offset
CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
CONNECT_GROUP_ID=dev-market-kafka_sink
# authentication
CONNECT_BOOTSTRAP_SERVERS=<KAFKA_HOSTNAME>:9092
CONNECT_SASL_MECHANISM=PLAIN
CONNECT_SECURITY_PROTOCOL=SASL_SSL
CONNECT_CONSUMER_BOOTSTRAP_SERVERS=<KAFKA_HOSTNAME>:9092
CONNECT_CONSUMER_SASL_MECHANISM=PLAIN
CONNECT_CONSUMER_SECURITY_PROTOCOL=SASL_SSL
# parsing
CONNECT_FORMAT_CLASS=io.confluent.connect.s3.format.json.JsonFormat
CONNECT_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
CONNECT_STORAGE_CLASS=io.confluent.connect.s3.storage.S3Storage
# logging
CONNECT_LOG4J_ROOT_LOGLEVEL=ERROR
# misc
CONNECT_PLUGIN_PATH=/usr/share/java,/etc/kafka-connect/jars
CONNECT_REQUEST_TIMEOUT_MS=20000
CONNECT_REST_ADVERTISED_HOST_NAME=localhost
CONNECT_REST_PORT=8083
CONNECT_RETRY_BACKOFF_MS=500
CONNECT_SCHEMA_COMPATABILITY=NONE
```

**Comment by asantoz** [comment]
I already had the same problem with SSL authentication and my solution was added producer and consumer env vars.

At the first moment, I only use this vars

`
        CONNECT_BOOTSTRAP_SERVERS: "kafka1:9094,kafka2:9094,kafka3:9094"
        CONNECT_SECURITY_PROTOCOL: SSL
        CONNECT_SSL_TRUSTSTORE_LOCATION: /root/kafka_credentials/truststore.jks
        CONNECT_SSL_TRUSTSTORE_PASSWORD: PASSWORD
        CONNECT_SSL_KEYSTORE_LOCATION: /root/kafka_credentials/client-keystore.jks
        CONNECT_SSL_KEYSTORE_PASSWORD: PASSWORD
        CONNECT_SSL_KEY_PASSWORD: PASSWORD
`
To solve this issue I added this ones too :point_down: 

`
# Producer config
CONNECT_PRODUCER_SECURITY_PROTOCOL: SSL
CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION: /root/kafka_credentials/truststore.jks
CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD: <PASSWORD>
CONNECT_PRODUCER_SSL_KEYSTORE_LOCATION: /root/kafka_credentials/client-keystore.jks
CONNECT_PRODUCER_SSL_KEYSTORE_PASSWORD: <PASSWORD>
CONNECT_PRODUCER_SSL_KEY_PASSWORD: <PASSWORD>

# Consumer Config
CONNECT_CONSUMER_SECURITY_PROTOCOL: SSL
CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION: /root/kafka_credentials/truststore.jks
CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD: <PASSWORD>
CONNECT_CONSUMER_SSL_KEYSTORE_LOCATION: /root/kafka_credentials/client-keystore.jks
CONNECT_CONSUMER_SSL_KEYSTORE_PASSWORD: <PASSWORD>
CONNECT_CONSUMER_SSL_KEY_PASSWORD: <PASSWORD>
`
I hope it helps guys! :pray: 

@kkonstantine Do you know if there is any reason to consumer and producer don't inherit by default the main SSL configurations?

Cheers!

**Comment by ynfialho** [comment]
> I already had the same problem with SSL authentication and my solution was added producer and consumer env vars.
> 
> At the first moment, I only use this vars
> 
> ```
> CONNECT_BOOTSTRAP_SERVERS: "kafka1:9094,kafka2:9094,kafka3:9094"
> CONNECT_SECURITY_PROTOCOL: SSL
> CONNECT_SSL_TRUSTSTORE_LOCATION: /root/kafka_credentials/truststore.jks
> CONNECT_SSL_TRUSTSTORE_PASSWORD: PASSWORD
> CONNECT_SSL_KEYSTORE_LOCATION: /root/kafka_credentials/client-keystore.jks
> CONNECT_SSL_KEYSTORE_PASSWORD: PASSWORD
> CONNECT_SSL_KEY_PASSWORD: PASSWORD
> ```
> 
> To solve this issue I added this ones too 
> 
> Producer config
> 
> ```
> CONNECT_PRODUCER_SECURITY_PROTOCOL: SSL
> CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION: /root/kafka_credentials/truststore.jks
> CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD: <PASSWORD>
> CONNECT_PRODUCER_SSL_KEYSTORE_LOCATION: /root/kafka_credentials/client-keystore.jks
> CONNECT_PRODUCER_SSL_KEYSTORE_PASSWORD: <PASSWORD>
> CONNECT_PRODUCER_SSL_KEY_PASSWORD: <PASSWORD>
> ```
> 
> Consumer Config
> 
> ```
> CONNECT_CONSUMER_SECURITY_PROTOCOL: SSL
> CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION: /root/kafka_credentials/truststore.jks
> CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD: <PASSWORD>
> CONNECT_CONSUMER_SSL_KEYSTORE_LOCATION: /root/kafka_credentials/client-keystore.jks
> CONNECT_CONSUMER_SSL_KEYSTORE_PASSWORD: <PASSWORD>
> CONNECT_CONSUMER_SSL_KEY_PASSWORD: <PASSWORD>
> ```
> 
> I hope it helps guys! 
> 
> @kkonstantine Do you know if there is any reason to consumer and producer don't inherit by default the main SSL configurations?
> 
> Cheers!

Thank @asantoz saved my day! :heart:
