### ISSUE TITLE
S3 Connector fails when DLQ is enabled

### ISSUE THREAD

**Issue by joaomaiaduarte** [confluentinc/kafka-connect-storage-cloud#194]
I am trying the new bad data handling feature and tasks fail once they receive bad data and dead letter queue functionality is enabled (i.e. `"errors.deadletterqueue.topic.name": "error_topic_name"`).
Task trace:
```
java.lang.NullPointerException
	at org.apache.kafka.connect.runtime.errors.DeadLetterQueueReporter.report(DeadLetterQueueReporter.java:124)
	at org.apache.kafka.connect.runtime.errors.ProcessingContext.report(ProcessingContext.java:137)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:108)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:513)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:490)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
If I disable dead letter queue (``"errors.deadletterqueue.topic.name": ""`), the connector skips the bad record as excepted and error logging works fine.

Am I missing something? Below there's my error-related configurations:
```
    "errors.retry.timeout": "300000",
    "errors.retry.delay.max.ms": "60000",
    "errors.log.enable": "true",
    "errors.log.include.messages": "true",
    "errors.tolerance": "all",
    "errors.deadletterqueue.topic.replication.factor": 1,
    "errors.deadletterqueue.topic.name": "error_topic_name",
    "errors.deadletterqueue.context.headers.enable": true
```

Thanks in advance!

**Comment by kkonstantine** [comment]
Hi @joaomaiaduarte 

you are hitting an unfortunate bug described here: 
https://issues.apache.org/jira/browse/KAFKA-7228

The fix has been merged and will be present in the next bugfix release of the [Connect framework](https://github.com/apache/kafka)

Closing here, since it's not a connector issue (and again has been fixed).

**Comment by Patafix** [comment]
Any workaround ? I use the docker image confluentinc/cp-kafka-connect:5.0.0

**Comment by kkonstantine** [comment]
@Patafix there is no workaround that will allow you to use the DLQ with 5.0.0. 
However, the bugfix release has been schedule for Apache Kafka: https://cwiki.apache.org/confluence/display/KAFKA/Release+Plan+2.0.1
targeting Oct 2018 and the Confluent bugfix release 5.0.1 should follow soon after.
