### ISSUE TITLE
When a S3 Connector Sink Task Fails from sprodic AWS Errors, the connector requires manual restart

### ISSUE THREAD

**Issue by Boblogic07** [confluentinc/kafka-connect-storage-cloud#225]
When an S3 Sink Task encounters a sporadic AWS S3 Error such as a 500 Internal Server Error, the task fails and requires a manual restart. 

From the status below:
- All other tasks are functioning normally.
- The Complete Multi-part Upload failed with an Access Denied error. This was a sporadic infrequent error that is exceedingly difficult to reproduce. We believe it is caused by the request occasionally taking more than 10 seconds to respond and a second request to upload the same object completes.
- The task remains failed despite the error being sporadic and exceedingly rare.

The same behavior can be observed with the occasional 500 internal server errors from AWS

Any suggestions on how to avoid the need to build and maintain an auto restart framework around the connector so that sporadic errors can be handled/ignored?

```
{
  "name": "connector-name",
  "connector": {
    "state": "RUNNING",
    "worker_id": "x.x.x.x:x"
  },
  "tasks": [
    {
      "state": "RUNNING",
      "id": 0,
      "worker_id": "x.x.x.y:x"
    },
    {
      "state": "RUNNING",
      "id": 1,
      "worker_id": "x.x.x.z:x"
    },
    {
      "state": "RUNNING",
      "id": 2,
      "worker_id": "x.x.x.x:x"
    },
    {
      "state": "RUNNING",
      "id": 3,
      "worker_id": "x.x.x.y:x"
    },
    {
      "state": "RUNNING",
      "id": 4,
      "worker_id": "x.x.x.z:x"
    },
    {
      "state": "FAILED",
      "trace": "org.apache.kafka.connect.errors.ConnectException: Exiting Worker SinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Multipart upload failed to complete.
	at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:160)
	at io.confluent.connect.s3.format.bytearray.ByteArrayRecordWriterProvider$1.commit(ByteArrayRecordWriterProvider.java:79)
	at io.confluent.connect.s3.TopicPartitionWriter.commitFile(TopicPartitionWriter.java:503)
	at io.confluent.connect.s3.TopicPartitionWriter.commitFiles(TopicPartitionWriter.java:483)
	at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:223)
	at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:176)
	at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:195)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
	... 10 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: XXXXXXXXXXX), S3 Extended Request ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4185)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4132)
	at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:2933)
	at io.confluent.connect.s3.storage.S3OutputStream$MultipartUpload.complete(S3OutputStream.java:246)
	at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:156)
	... 17 more
",
      "id": 5,
      "worker_id": "x.x.x.x:x"
    },
    {
      "state": "RUNNING",
      "id": 6,
      "worker_id": "x.x.x.y:x"
    },
    {
      "state": "RUNNING",
      "id": 7,
      "worker_id": "x.x.x.z:x"
    },
    {
      "state": "RUNNING",
      "id": 8,
      "worker_id": "x.x.x.x:x"
    },
    {
      "state": "RUNNING",
      "id": 9,
      "worker_id": "x.x.x.y:x"
    }
  ],
  "type": "sink"
}
```

**Comment by bhaveshraheja** [comment]
Same. Seeing this quite often. A restart of the task usually fixes this.

**Comment by aakashnshah** [comment]
The newest version of the connector should retry this type of error I believe. If not, this is enhancement that can be added as part of a retriable exception.
