### ISSUE TITLE
Serialization exceptions due to "Invalid UTF-32 character 0x3f71e167 (above 0x0010ffff)"

### ISSUE THREAD

**Issue by hashhar** [confluentinc/kafka-connect-storage-cloud#229]
```
Caused by: org.apache.kafka.common.errors.SerializationException: java.io.CharConversionException: Invalid UTF-32 character 0x3f71e167 (above 0x0010ffff) at char #3, byte #15)
Caused by: java.io.CharConversionException: Invalid UTF-32 character 0x3f71e167 (above 0x0010ffff) at char #3, byte #15)
        at com.fasterxml.jackson.core.io.UTF32Reader.reportInvalid(UTF32Reader.java:195)
        at com.fasterxml.jackson.core.io.UTF32Reader.read(UTF32Reader.java:158)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:243)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2331)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:646)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4030)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2559)
        at org.apache.kafka.connect.json.JsonDeserializer.deserialize(JsonDeserializer.java:50)
        at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:332)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:467)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:301)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I repeatedly see this error until all my S3 connector tasks die.

Is there any way I can figure out what message is causing this.

Here's my connector config:

```json
{
  "name": "s3-sink",
  "config": {
    "connector.class": "io.confluent.connect.s3.S3SinkConnector",
    "topics.regex": "(dwh_connector|dwh_transformer).*",
    "tasks.max": "10",
    "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
    "flush.size": "10000",
    "rotate.interval.ms": "3600000",
    "rotate.schedule.interval.ms": "3600000",
    "s3.bucket.name": "xxxxx",
    "s3.region": "ap-southeast-1",
    "s3.compression.type": "gzip",
    "storage.class": "io.confluent.connect.s3.storage.S3Storage",
    "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
    "partition.duration.ms": "3600000",
    "path.format": "YYYY/MM/dd/HH",
    "locale": "en",
    "timezone": "UTC",
    "timestamp.extractor": "Record"
  }
}
```

The messages in the `dwh_connector.*` topics are from Debezium in JSON format with both key and value schemas disabled.

The messages in `dwh_transformer1` have empty string keys, and connect data format JSON (ie. `schema` and `payload` keys) to be consumed by a JDBC sink.  
The messages in `dwh_transformer2` have empty string keys and flat JSON without `schema` or `payload` keys.

I've set `key.converter.schemas.enable: false` and `value.converter.schemas.enable: false` in my connect worker properties.

**Comment by hashhar** [comment]
Fixed after using `"key.converter": "org.apache.kafka.connect.storage.StringConverter"`. Empty strings are not valid JSON according to the JSON RFC.
