### ISSUE TITLE
S3 connector - intermittent no route to host - does not retry

### ISSUE THREAD

**Issue by csghuser** [confluentinc/kafka-connect-storage-cloud#235]
We have kafka-connect configured with a number of topics, all writing out to s3. 

The version of the s3 connector we are using is:

`confluent-kafka-connect-s3-4.1.2-1.noarch`

The connector is running outside of AWS. The following error was seen:

```
[2019-03-19 01:01:49,189] INFO Files committed to S3. Target commit offset for some-topic-0 is 28425321 (io.confluent.connect.s3.TopicPartitionWriter:491)
[2019-03-19 01:01:55,466] ERROR Multipart upload failed to complete for bucket 'some-aws-bucket' key 'some-dest/somefile..json' (io.confluent.connect.s3.storage.S3OutputStream:162)
[2019-03-19 01:01:55,466] ERROR WorkerSinkTask{id=some-topic-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:544)
org.apache.kafka.connect.errors.DataException: Multipart upload failed to complete.
        at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:163)
        at io.confluent.connect.s3.format.json.JsonRecordWriterProvider$1.commit(JsonRecordWriterProvider.java:98)
        at io.confluent.connect.s3.TopicPartitionWriter.commitFile(TopicPartitionWriter.java:503)
        at io.confluent.connect.s3.TopicPartitionWriter.commitFiles(TopicPartitionWriter.java:483)
        at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:223)
        at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:176)
        at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:195)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:524)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:302)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unable to initiate MultipartUpload: com.amazonaws.SdkClientException: Unable to execute HTTP request: No route to host (Host unreachable)
        at io.confluent.connect.s3.storage.S3OutputStream.newMultipartUpload(S3OutputStream.java:209)
        at io.confluent.connect.s3.storage.S3OutputStream.uploadPart(S3OutputStream.java:126)
        at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:157)
        ... 17 more
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: No route to host (Host unreachable)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1043)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4185)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4132)
        at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3017)
        at io.confluent.connect.s3.storage.S3OutputStream.newMultipartUpload(S3OutputStream.java:205)
        ... 19 more
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
```

Looking at the logs it does not appear to have retried. This is despite the following default value appearing in the logs for the connectors:

```
s3.part.retries = 3
```

**Comment by csghuser** [comment]
Looks as though at the moment the error is caught, but it is not retrying:

https://github.com/niksajakovljevic/kafka-connect-storage-cloud/blob/master/kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java#L171

**Comment by Thoymas** [comment]
We are seeing a similar problem, although the root cause is request throttling from the S3 side. Example error message:

```2019-08-26 07:00:08,753 ERROR org.apache.kafka.connect.runtime.WorkerTask:177 - WorkerSinkTask{id=<anonymized>} Task threw an uncaught and unrecoverable exception
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Multipart upload failed to complete.
	at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:158)
	at io.confluent.connect.s3.format.json.JsonRecordWriterProvider$1.commit(JsonRecordWriterProvider.java:96)
	at io.confluent.connect.s3.TopicPartitionWriter.commitFile(TopicPartitionWriter.java:503)
	at io.confluent.connect.s3.TopicPartitionWriter.commitFiles(TopicPartitionWriter.java:483)
	at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:221)
	at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:174)
	at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)
	... 10 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Please reduce your request rate. (Service: Amazon S3; Status Code: 503; Error Code: SlowDown; Request ID: B98CD820B62BDFC2), S3 Extended Request ID: r0slVp+ZDBtVVP3YTvS9us+VrJTkmYyblUGO/UrRlASbyLGfOnqFGatc4/70RvThBlG4gNBaa7k=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4185)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4132)
	at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:2933)
	at io.confluent.connect.s3.storage.S3OutputStream$MultipartUpload.complete(S3OutputStream.java:244)
	at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:154)
	... 17 more
``` 

This is causing data loss in our S3 pipelines. We seem to be able to repair the gaps by quering for incomplete multipartuploads and manually committing them afterwards but this is no solution.

Getting throttled from S3 should be expected and in these cases I expect the connector to retry until it succeeds or at least until the retries configured have been exhausted.

We are running the s3-connector from
`confluent-kafka-connect-s3.noarch   5.1.2-1`

Best Regards
/Thomas

**Comment by lkam-spireon** [comment]
We have several Kafka Connect instances with S3 sinks deployed into production.  Every now and then, one of those instances will go down and we have to restart them.  It looks like sometimes a network issue will arise and, as @csghuser pointed out, there's no retry logic within the method `io.confluent.connect.s3.storage.S3OutputStream.newMultipartUpload`.  So, the instance will just remain dead until restarted.  In this case, there was some sort of DNS issue which resulted in one of our pipelines going down.  I believe in error cases such as these, the sink should execute a number of retries before throwing the exception all the way up the chain.

`org.apache.kafka.connect.errors.DataException: Multipart upload failed to complete.
	at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:159)
	at io.confluent.connect.s3.format.json.JsonRecordWriterProvider$1.commit(JsonRecordWriterProvider.java:97)
	at io.confluent.connect.s3.TopicPartitionWriter.commitFile(TopicPartitionWriter.java:503)
	at io.confluent.connect.s3.TopicPartitionWriter.commitFiles(TopicPartitionWriter.java:483)
	at io.confluent.connect.s3.TopicPartitionWriter.commitOnTimeIfNoData(TopicPartitionWriter.java:294)
	at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:184)
	at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unable to initiate MultipartUpload: com.amazonaws.SdkClientException: Unable to execute HTTP request: s3.amazonaws.com
	at io.confluent.connect.s3.storage.S3OutputStream.newMultipartUpload(S3OutputStream.java:207)
	at io.confluent.connect.s3.storage.S3OutputStream.uploadPart(S3OutputStream.java:127)
	at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:153)
	... 17 more
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: s3.amazonaws.com
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1043)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4185)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4132)
	at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3017)
	at io.confluent.connect.s3.storage.S3OutputStream.newMultipartUpload(S3OutputStream.java:203)
	... 19 more
Caused by: java.net.UnknownHostException: s3.amazonaws.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy43.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1186)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	... 29 more`
