### ISSUE TITLE
"SchemaParseException: Can't redefine" error if there are docs in the schema

### ISSUE THREAD

**Issue by umutgulkok** [confluentinc/kafka-connect-storage-cloud#239]
We use s3-sink to transfer our avro serialized data in Kafka to an S3 bucket.
Our connector tasks give errors like “org.apache.avro.SchemaParseException: Can’t redefine: <record schema name>”
This happens only if there are multiple fields in the avdl file with the same record type and at least one of these fields have a comment. If we remove the comments from the avdl file, it works fine.
Might there be a bug? This behaviour is very strange.

**Details:**
Confluent platform version: 5.1.2
The data:
```
{
  "screen": {
    "val": 1
  },
  "viewport": {
    "val": 2
  }
}
```

The avdl file:
```
@namespace("com.mycompany")
protocol MyEventProtocol {

  record SubRecord {
    int val;
  }

  record MyEvent {
    /**
    Comment 1
    */
    SubRecord screen;

    /**
    Comment 2
    */
    SubRecord viewport;
  }
}
```

The produced avsc file:
```
{
    "type": "record",
    "name": "MyEvent",
    "namespace": "com.mycompany",
    "fields": [
        {
            "name": "screen",
            "type": {
                "type": "record",
                "name": "SubRecord",
                "fields": [
                    {
                        "name": "val",
                        "type": "int"
                    }
                ]
            },
            "doc": "Comment 1"
        },
        {
            "name": "viewport",
            "type": "SubRecord",
            "doc": "Comment 2"
        }
    ]
}
```

The error comming from the kafka-connect tasks:
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.avro.SchemaParseException: Can't redefine: com.mycompany.Subrecord
at org.apache.avro.Schema$Names.put(Schema.java:1128)
at org.apache.avro.Schema$NamedSchema.writeNameRef(Schema.java:562)
at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:690)
at org.apache.avro.Schema$RecordSchema.fieldsToJson(Schema.java:716)
at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:701)
at org.apache.avro.Schema$RecordSchema.fieldsToJson(Schema.java:716)
at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:701)
at org.apache.avro.Schema.toString(Schema.java:324)
at org.apache.avro.Schema.toString(Schema.java:314)
at org.apache.avro.file.DataFileWriter.create(DataFileWriter.java:144)
at org.apache.avro.file.DataFileWriter.create(DataFileWriter.java:135)
at io.confluent.connect.s3.format.avro.AvroRecordWriterProvider$1.write(AvroRecordWriterProvider.java:70)
at io.confluent.connect.s3.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:477)
at io.confluent.connect.s3.TopicPartitionWriter.checkRotationOrAppend(TopicPartitionWriter.java:265)
at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:210)
at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:174)
at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:193)
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)
... 10 more
```

The connector config:
```
```{
    "name": "s3-sink",
    "config": {
        "connector.class": "io.confluent.connect.s3.S3SinkConnector",
        "tasks.max": "10",
        "topics": "MyEvent",
        "topics.dir": "events",
        "s3.region": "us-east-1",
        "s3.bucket.name": "mybucket",
        "s3.part.size": "100000000",
        "flush.size": "1",
        "storage.class": "io.confluent.connect.s3.storage.S3Storage",
        "format.class": "io.confluent.connect.s3.format.avro.AvroFormat",
        "schema.generator.class": "io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator",
        "partitioner.class": "io.confluent.connect.storage.partitioner.HourlyPartitioner",
        "schema.compatibility": "BACKWARD",
        "locale": "en-US",
        "timezone": "GMT-0",
        "name": "s3-sink"
    }
}
```

**Comment by cricket007** [comment]
In some cases, this can be solved with the property `connect.meta.data=false`

**Comment by cricket007** [comment]
The documentation is a bit sparse on it. I had to look through source code to find what it does

https://github.com/confluentinc/schema-registry/blob/master/avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java

But from what I've seen, Connect writes extra properties on the output Avro file schema metadata. If you have other S3 connects working, you can use avro-tools jar to `getschema` command to compare

**Comment by umutgulkok** [comment]
This solved our problem. Thank you.

**Comment by nivemaham** [comment]
@umutgulkok @cricket007 Could you please tell  how exactly did you do this configuration?
I tried adding this to AvroData through AvroDataConfig. It didn't seem to fix the issue

**Comment by cricket007** [comment]
`value.converter.connect.meta.data=false`

**Comment by nivemaham** [comment]
> `value.converter.connect.meta.data=false`

Thanks a lot for the prompt response.
Just to be sure, this can be added to the connector config file. (i.e. connect.source.properties) file?

**Comment by cricket007** [comment]
It can be added anywhere you've also defined the schema registry URL

**Comment by nivemaham** [comment]
Thanks for your update. We ran into this issue on a source-connector using `confluentinc/cp-kafka-connect-base:5.3.0` docker image.
For that we had to add the env variable `CONNECT_VALUE_CONVERTER_CONNECT_META_DATA=false` to get this work.
