### ISSUE TITLE
Schema containing record with '{}' as default value not supported

### ISSUE THREAD

**Issue by laymain** [confluentinc/kafka-connect-storage-cloud#242]
Hi,

We have been facing an issue by using an empty object as default value of a record in a Schema,
when we try to copy avro data to S3, connector fails with the following exception:
`AvroRuntimeException: Unknown datum class: class org.apache.kafka.connect.data.Struct`

I've been able to reproduce the error with a simplified schema.

---

## Steps to reproduce ##

* Create a schema with an empty object as default value of a record:
```javascript
{
  "type": "record",
  "name": "KafkaConnectFailure",
  "namespace": "com.laymain.avro",
  "fields": [
    {
      "name": "inner",
      "type": {
        "type": "record",
        "name": "InnerRecord",
        "namespace": "com.laymain.avro",
        "fields": [
          {
            "name": "str",
            "type": {
              "type": "string",
              "avro.java.string": "String"
            }
          }
        ]
      },
      "default": {}
    }
  ]
}
```

* Produce messages in a topic, ie: _topic-kafka-connect-fails_
```javascript
// json representation of a message
{"inner": {"str": null}}
```

* Configure a connector to copy data from kafka to S3
```javascript
{
  "avro.codec": "deflate",
  "connector.class": "io.confluent.connect.s3.S3SinkConnector",
  "format.class": "io.confluent.connect.s3.format.avro.AvroFormat",
  "name": "kafka-connect-fails",
  "schema.compatibility": "NONE",
  "schema.generator.class": "io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator",
  "storage.class": "io.confluent.connect.s3.storage.S3Storage",
  "tasks.max": "1",
  "locale": "en",
  "timezone": "UTC",
  "s3.region": "eu-west-1",
  "s3.bucket.name": "com.laymain.bucket",
  "topics": "kafka-connect-fails",
  "topics.dir": "kafka-connect-fails",
  "flush.size": "10" 
}
```

---

## Result ##

The connector fails with the following error

```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.avro.AvroRuntimeException: Unknown datum class: class org.apache.kafka.connect.data.Struct
    at org.apache.avro.util.internal.JacksonUtils.toJson(JacksonUtils.java:87)
    at org.apache.avro.util.internal.JacksonUtils.toJsonNode(JacksonUtils.java:48)
    at org.apache.avro.Schema$Field.<init>(Schema.java:423)
    at org.apache.avro.Schema$Field.<init>(Schema.java:415)
    at io.confluent.connect.avro.AvroData.addAvroRecordField(AvroData.java:1016)
    at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:883)
    at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:725)
    at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:719)
    at io.confluent.connect.s3.format.avro.AvroRecordWriterProvider$1.write(AvroRecordWriterProvider.java:68)
    at io.confluent.connect.s3.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:477)
    at io.confluent.connect.s3.TopicPartitionWriter.checkRotationOrAppend(TopicPartitionWriter.java:265)
    at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:210)
    at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:174)
    at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:193)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)
    ... 10 more
```

Whereas, I have no problem handling this schema using Avro directly.
I think the [AvroData](https://github.com/confluentinc/schema-registry/blob/96e26faf81d8bb049ff4015ef44470551f82de2d/avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java#L1063) class lacks the support of empty object as default value for a record.

**Comment by cricket007** [comment]
Note: This issue isn't specific to S3. The converter module is here

https://github.com/confluentinc/schema-registry/tree/master/avro-converter

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/schema-registry/pull/1357

**Comment by laymain** [comment]
That's nice, thanks, we still have the need
