### ISSUE TITLE
assume-role auth not implemented (Always Access Denied on S3 multipart upload)

### ISSUE THREAD

**Issue by Hubbitus** [confluentinc/kafka-connect-storage-cloud#260]
I always got exceptions like:
```
[2019-07-22 16:47:34,877] ERROR WorkerSinkTask{id=tmp__t1-to-s3-34-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Multipart upload failed to complete.
        at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:159)
        at io.confluent.connect.s3.format.json.JsonRecordWriterProvider$1.commit(JsonRecordWriterProvider.java:97)
        at io.confluent.connect.s3.TopicPartitionWriter.commitFile(TopicPartitionWriter.java:504)
        at io.confluent.connect.s3.TopicPartitionWriter.commitFiles(TopicPartitionWriter.java:484)
        at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:222)
        at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:175)
        at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:194)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
        ... 10 more
Caused by: java.io.IOException: Unable to initiate MultipartUpload: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 7F74CF3EB2B48AF3), S3 Extended Request ID: rzgwmif4OCCej4r3ckkOlXuh/SaPZgRNzYnOejpKcvws7qChmA7Gdfm5K5bk8l+QU3jdSRcTlf0=
        at io.confluent.connect.s3.storage.S3OutputStream.newMultipartUpload(S3OutputStream.java:207)
        at io.confluent.connect.s3.storage.S3OutputStream.uploadPart(S3OutputStream.java:127)
        at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:153)
        ... 17 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 7F74CF3EB2B48AF3), S3 Extended Request ID: rzgwmif4OCCej4r3ckkOlXuh/SaPZgRNzYnOejpKcvws7qChmA7Gdfm5K5bk8l+QU3jdSRcTlf0=
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4185)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4132)
        at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3017)
        at io.confluent.connect.s3.storage.S3OutputStream.newMultipartUpload(S3OutputStream.java:203)
        ... 19 more
```

What interesting, error similar with all tried auth providers:
- com.amazonaws.auth.InstanceProfileCredentialsProvider
- com.amazonaws.auth.EnvironmentVariableCredentialsProvider
- com.amazonaws.auth.profile.ProfileCredentialsProvider

It is run from `debezium/connect:0.10` docker image. Connector version 5.2.2.
I've checked my credentials and provided `aws_access_key_id`/`aws_secret_access_key` pair works via `awscli`.
**But! It works on awscli version 1.14.28 and did not work under version 1.4.2 (default debian version available in apt repos in container)!** So it looks like something changed in authorization procedure and/or algorithm.
Could you please advise me how I can troubleshoot it further??

**Comment by Hubbitus** [comment]
I've found the reason of fail.
In our configuration assume-role used for access. So there needs to be something like https://github.com/Nordstrom/kafka-connect-assume-role

Could you please incorporate it into kafka-connect by default? Or at least document such case. I spent many hours for searching and debugging until understand that.

**Comment by dylanmei** [comment]
There's also a PR for this: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/230

**Comment by kkonstantine** [comment]
Fixed by: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/311 that was based on https://github.com/confluentinc/kafka-connect-storage-cloud/pull/230
Closing this issue as resolved. Please open a new one if there's a gap.
