### ISSUE TITLE
Elasticsearch Connector fails when DLQ is enabled

### ISSUE THREAD

**Issue by arnitolog** [confluentinc/kafka-connect-storage-cloud#275]
I tried to enable DLQ functionality for my connector. The configuration is below:

```
 "name" : "es_sink",
 "config" : {
  "connector.class" : "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "tasks.max" : "2",
  "topics.regex" : "logging-(.+)",
  "connection.url" : "https://logging-cluster-es:9200",
  "connection.username": "logger",
  "connection.password": "xxxxxxxxxxx",
  "behavior.on.malformed.documents": "warn",
  "errors.deadletterqueue.topic.name": "deadletterqueue-logging",
  "errors.deadletterqueue.context.headers.enable": "true",
  "type.name" : "_doc",
  "key.ignore" : "true",
  "schema.ignore" : "true",
  "schemas.enable": "false",
  "key.converter.schemas.enable":"false",'
  "value.converter.schemas.enable":"false",
```
But once I enabled it, I got an error and connector couldn't start: 

`{"name":"es_sink","connector":{"state":"RUNNING","worker_id":"100.102.66.106:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"100.102.66.106:8083","trace":"org.apache.kafka.connect.errors.ConnectException: Could not initialize dead letter queue with topic=deadletterqueue-logging
at org.apache.kafka.connect.runtime.errors.DeadLetterQueueReporter.createAndSetup(DeadLetterQueueReporter.java:89)
at org.apache.kafka.connect.runtime.Worker.sinkTaskReporters(Worker.java:660)
at org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:524)
at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:459)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1036)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:117)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:1051)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:1047)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)\nCaused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
at org.apache.kafka.connect.runtime.errors.DeadLetterQueueReporter.createAndSetup(DeadLetterQueueReporter.java:80)
... 11 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment."}`

without this option, the connector works as expected. So, I'm curious is it a bug, or I missed some config?

**Comment by THEjoezack** [comment]
Did you end up figuring this out @arnitolog ? I'm seeing the same thing.
