### ISSUE TITLE
contains no connector type

### ISSUE THREAD

**Issue by msilvestre** [confluentinc/kafka-connect-storage-cloud#287]
I'm trying to set this connector on my local machine. However I'm getting the error below over and over:

Any idea on what am I doing wrong?
Thanks,

[2019-11-12 16:12:54,655] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:56)
[2019-11-12 16:12:54,659] ERROR Failed to create job for /Users/miguel.silvestre/quickstart-s3.properties (org.apache.kafka.connect.cli.ConnectStandalone:110)
[2019-11-12 16:12:54,659] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:121)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector config {"schema.generator.class"="io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator",, "tasks"=[], "config"={, "s3.part.size"="5242880",, "s3.bucket.name"="test-connector",, "connector.class"="io.confluent.connect.s3.S3SinkConnector",, "format.class"="io.confluent.connect.s3.format.avro.AvroFormat",, },=, "tasks.max"="1",, "s3.region"="eu-west-1",, "partitioner.class"="io.confluent.connect.storage.partitioner.DefaultPartitioner",, "name"="s3-sink", "flush.size"="3",, "schema.compatibility"="NONE",, {=, "storage.class"="io.confluent.connect.s3.storage.S3Storage",, "topics"="test",, }=} contains no connector type
	at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:118)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector config {"schema.generator.class"="io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator",, "tasks"=[], "config"={, "s3.part.size"="5242880",, "s3.bucket.name"="test-connector",, "connector.class"="io.confluent.connect.s3.S3SinkConnector",, "format.class"="io.confluent.connect.s3.format.avro.AvroFormat",, },=, "tasks.max"="1",, "s3.region"="eu-west-1",, "partitioner.class"="io.confluent.connect.storage.partitioner.DefaultPartitioner",, "name"="s3-sink", "flush.size"="3",, "schema.compatibility"="NONE",, {=, "storage.class"="io.confluent.connect.s3.storage.S3Storage",, "topics"="test",, }=} contains no connector type
	at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:287)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:192)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)

**Comment by cricket007** [comment]
What does your property file look like?

Seems like there's extra brackets and commas `S3Storage",, "topics"="test",, }=}`... Is your file actually JSON, not a properties file?
