### ISSUE TITLE
Azureblobstorage kafka source connector

### ISSUE THREAD

**Issue by ankit302** [confluentinc/kafka-connect-storage-cloud#303]
Hi,

I'm trying to read data stored in a JSON file kept in azure blob storage & store it to kafka topics with the help of confluent azureblobstorage connector.

I have gone through the documentation but it's seems to configuration parameters for connector is little complex w.r.t to standard directory structure in azure blob storage to make it working.

Below source connector is not working for me, it's failing with error;

Not sure what i'm missing in terms of blob storage directory, any suggestions / pointers will  help.

Do you have any example which i can refer to configure the connectors ?

Error log:-

ERROR WorkerConnector{id=AzureBlobStorageSourceConnector} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector) [pool-5-thread-8]
org.apache.kafka.connect.errors.ConnectException: Error while getting list of folders from Azure Blob Storage Container
        at io.confluent.connect.azure.blob.storage.AzureBlobSourceStorage.listFolders(AzureBlobSourceStorage.java:262)
        at io.confluent.connect.storage.partitioner.DefaultPartitioner.calculatePartitions(DefaultPartitioner.java:53)
        at io.confluent.connect.storage.partitioner.DefaultPartitioner.getPartitions(DefaultPartitioner.java:40)
        at io.confluent.connect.cloud.storage.source.AbstractCloudStorageSourceConnector.doStart(AbstractCloudStorageSourceConnector.java:82)
        at io.confluent.connect.cloud.storage.source.AbstractCloudStorageSourceConnector.start(AbstractCloudStorageSourceConnector.java:73)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
        at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
        at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:252)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1079)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:117)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:1095)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:1091)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at io.confluent.connect.azure.blob.storage.AzureBlobSourceStorage.listFolders(AzureBlobSourceStorage.java:251)
        ... 16 more

Source Connector config:-

{
  "name" : "AzureBlobStorageSourceConnector",
  "config" : {
    "connector.class" : "io.confluent.connect.azure.blob.storage.AzureBlobStorageSourceConnector",
    "tasks.max" : "1",
"plugin.path" : "/opt/kafka/plugins/my-plugins",
    "azblob.account.name" : "STORAGE_ACCOUNT_NAME",
    "azblob.account.key" : "ACCESS_KEY_OF_THE_ACCOUNT",
    "azblob.container.name" : "BLOB_CONTAINER_NAME",
    "format.class" : "io.confluent.connect.azure.blob.storage.format.json.JsonFormat",
    "confluent.topic.bootstrap.servers" : "my-cluster-kafka-bootstrap:9092",
    "confluent.topic.replication.factor" : "3",
"record.batch.max.size" : "300",
    "transforms" : "AddPrefix",
    "transforms.AddPrefix.type" : "org.apache.kafka.connect.transforms.RegexRouter",
    "transforms.AddPrefix.regex" : ".*",
    "transforms.AddPrefix.replacement" : "copy_of_$0"
  }
}

**Comment by NathanNam** [comment]
Hello, 

How is this json file populated in your Azure Blob Storage? At this moment, the Azure Blob Storage Source Connector only supports records populated by Azure Blob Storage Sink Connector.  https://docs.confluent.io/current/connect/kafka-connect-azure-blob-storage/source/index.html#az-blob-storage-source-connector-for-cp
