### ISSUE TITLE
 ERROR [Worker clientId=connect-1, groupId=kafka-s3-connector] Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:290)

### ISSUE THREAD

**Issue by dBadaya96** [confluentinc/kafka-connect-storage-cloud#307]
Getting **java.lang.NullPointerException**  while running **kafka-s3-connector** in **distributed mode**.

It works fine when I run in **standalone** mode

> Below is the stacktrace::

`	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:501)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:481)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:264)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:287)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:154)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:265)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:123)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:277)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)`

PFA the config files 

1. quickstart-s3.properties
2. connect-distributed.properties
[connect-distributed.txt](https://github.com/confluentinc/kafka-connect-storage-cloud/files/4236175/connect-distributed.txt)
[quickstart-s3.txt](https://github.com/confluentinc/kafka-connect-storage-cloud/files/4236177/quickstart-s3.txt)

**Comment by dBadaya96** [comment]
kafka version -> 2.3.1
confluent version -> 5.4.0
