### ISSUE TITLE
Class not found error when using parquet w/ zstd codec

### ISSUE THREAD

**Issue by luke-zhu** [confluentinc/kafka-connect-storage-cloud#316]
I tried to use parquet with zstd codec and faced an error (stacktrace below).

I believe this because zstd support was only added in Hadoop 2.9 ([JIRA Ticket](https://issues.apache.org/jira/browse/HADOOP-13578)) while this project uses v2.7.7.

```
[2020-03-21 21:17:40,156] ERROR WorkerSinkTask{id=bench10.schema-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.parquet.hadoop.BadConfigurationException: Class org.apache.hadoop.io.compress.ZStandardCodec was not found
	at org.apache.parquet.hadoop.CodecFactory.getCodec(CodecFactory.java:235)
	at org.apache.parquet.hadoop.CodecFactory$HeapBytesCompressor.<init>(CodecFactory.java:142)
	at org.apache.parquet.hadoop.CodecFactory.createCompressor(CodecFactory.java:206)
	at org.apache.parquet.hadoop.CodecFactory.getCompressor(CodecFactory.java:189)
	at org.apache.parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:285)
	at org.apache.parquet.hadoop.ParquetWriter$Builder.build(ParquetWriter.java:530)
	at io.confluent.connect.s3.format.parquet.ParquetRecordWriterProvider$1.write(ParquetRecordWriterProvider.java:80)
	at io.confluent.connect.s3.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:494)
	at io.confluent.connect.s3.TopicPartitionWriter.checkRotationOrAppend(TopicPartitionWriter.java:274)
	at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:219)
	at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:188)
	at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:190)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.io.compress.ZStandardCodec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.parquet.hadoop.CodecFactory.getCodec(CodecFactory.java:230)
	... 22 more
```

**Comment by BDeus** [comment]
i have the same issue, anybody use successfully zstd with parquet ?
