### ISSUE TITLE
NullPointerException in ParquetRecordWriterProvider

### ISSUE THREAD

**Issue by Step2Web** [confluentinc/kafka-connect-storage-cloud#324]
Hey guys, 

we're currently testing the S3SinkConnector and I'm noticing that since this morning, all tasks of the connector fail with the following exception:

```
[2020-04-21 10:12:58,241] ERROR WorkerSinkTask{id=iad_ad_s3_sink-8} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.NullPointerException
        at io.confluent.connect.s3.format.parquet.ParquetRecordWriterProvider$1.close(ParquetRecordWriterProvider.java:97)
        at io.confluent.connect.s3.TopicPartitionWriter.close(TopicPartitionWriter.java:313)
        at io.confluent.connect.s3.S3SinkTask.close(S3SinkTask.java:229)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:397)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:591)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

This is caused by 

```
[2020-04-21 10:20:48,722] ERROR WorkerSinkTask{id=iad_ad_s3_sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.OutOfMemoryError: Java heap space
```

However, the NPE is not very telling and it took me awhile to figure out what was going on.

Anyhow, not high priority but it would make it easier to debug.

**Comment by skecskes** [comment]
I have same error. I use s3 sink connector and I'am trying to consume protobuf messages from topic and save them into Parquet files in S3. I am using ProtobufConverter as value.converter. The ParquetFormat as format.class.

**Comment by remy-voodoo** [comment]
Hello,

Same here any clue on that ? Do you have a solution for that ?
Thank you.

**Comment by shanemougham** [comment]
Hello Guys,

I am getting exception while using Kafka S3 Sink Connector to write as Parquet Format to s3. 
 
java.lang.NoClassDefFoundError: com/google/common/base/Preconditions
        at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:361)
        at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:374)
        at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:456)
        at org.apache.parquet.hadoop.ParquetWriter$Builder.<init>(ParquetWriter.java:345)
        at org.apache.parquet.avro.AvroParquetWriter$Builder.<init>(AvroParquetWriter.java:162)
        at org.apache.parquet.avro.AvroParquetWriter$Builder.<init>(AvroParquetWriter.java:153)
        at org.apache.parquet.avro.AvroParquetWriter.builder(AvroParquetWriter.java:43)
        at io.confluent.connect.s3.format.parquet.ParquetRecordWriterProvider$1.write(ParquetRecordWriterProvider.java:74)
        at io.confluent.connect.s3.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:502)
        at io.confluent.connect.s3.TopicPartitionWriter.checkRotationOrAppend(TopicPartitionWriter.java:275)
        at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:220)
        at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:189)
        at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:191)

Below is config for S3 sink task connector.. 
 {
  "name": "s3-sink-test-21",
  "config": {
    "connector.class": "io.confluent.connect.s3.S3SinkConnector",
    "tasks.max": "1",
    "topics": "TESTREPLICA12",
    "s3.region": "ap-southeast-2",
    "s3.bucket.name": "apra-amcos-kafka-sink",
    "s3.part.size": "5242880",
    "flush.size": "1",
    "auto.register.schemas": "false",
    "storage.class": "io.confluent.connect.s3.storage.S3Storage",
    "schema.compatibility": "FULL",
    "locale": "AU",
    "timezone": "EST",
    "partitioner.class":"io.confluent.connect.storage.partitioner.DailyPartitioner",   
    "partition.duration.ms":"86400000",                                                                                                                                                                                                                              
    "rotate.interval.ms":"60000",                                                                                                                                                                                                                                   
    "timestamp.extractor":"Record", 
    "parquet.codec": "none",   
    "schema.generator.class": "io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",     
    "value.converter.schema.registry.url": "http://127.0.0.1:8081",
    "format.class": "io.confluent.connect.s3.format.parquet.ParquetFormat",
    "enhanced.avro.schema.support":"true",
    "path.format":"YYYY-MM-dd-HH"   
  }
}'

Please advise .

Regards
Shane

**Comment by samudurand** [comment]
Any update on this ? I have the same problem. I have at least 10 other connectors running and the java Heap is fine. But that particular connector is still failing.

**Comment by forsberg** [comment]
I see this a lot when in catchup mode. I.e, under normal operations, I can have a couple of instances of the Kafka Connect cluster running with a normal amount of memory, and all is fine.

If something has been going haywire and I have a backlog, then things start struggling, and I have to increase the number of instances in the cluster, and sometimes give them more memory too.

My suspicion is that this has to do with partitioning, I'm using the TimedbasedPartitioner with a duration of one hour, and in normal operations this means that the connector will have to keep a few dozens of partitions open due to the mix of topics and timeperiod data that comes in. During catchup however, the number of TopicPartitionWriter it has to keep in memory at the same time will skyrocket, and I'm guessing this is what causes memory exhaustion.
