### ISSUE TITLE
Avro input to Kafka Connect Fails

### ISSUE THREAD

**Issue by l2y** [confluentinc/kafka-connect-storage-cloud#338]
Hi, I'm trying to ingest Avro messages similar to the following (pre-serialized):
```
{
  "fields": [
    {
      "name": "event_timestamp",
      "type": [{
        "logicalType": "timestamp-millis",
        "type": "long"
      }]
    },
    {
      "name": "number_id",
      "type": ["long"],
      "default": 0
    },
    {
      "name": "string_id",
      "type": [
          "null",
          "string"
      ],
      "default": null
    }
  ],
  "name": "Event",
  "namespace": "namespace",
  "type": "record"
}
```

From Kafka into S3 using the following connector:

```
curl localhost:8083/connectors -XPOST -H'Content-type: application/json' -H'Accept: application/json' -d '{
	"name": "<CONNECTOR_NAME>",
	"config": {
		"topics": "<TOPIC_NAME_WITH_AVRO_DATA>",
		"connector.class": "io.confluent.connect.s3.S3SinkConnector",
		"tasks.max": "3",
		"topics.dir": "<DIRECTORY_NAME>",
		"s3.bucket.name": "<BUCKET_NAME>",
		"s3.part.size": "26214400",
		"flush.size": "10000",
		"storage.class": "io.confluent.connect.s3.storage.S3Storage",
		"format.class": "io.confluent.connect.s3.format.avro.AvroFormat",
		"partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
		"schema.compatibility": "NONE",
		"timezone": "UTC",
		"partition.duration.ms": "60000",
		"path.format": "'\''year'\''=YYYY/'\''month'\''=MM/'\''day'\''=dd/'\''hour'\''=HH/",
		"locale": "US",
		"timestamp.extractor": "Record",
		"rotate.schedule.interval.ms": "60000",
		"key.converter":"org.apache.kafka.connect.storage.StringConverter",
		"value.converter":"io.confluent.connect.avro.AvroConverter",
		"value.converter.schema.registry.url":"<SCHEMA_REGISTRY>"
	}
}'
```

However when running the connector, I get the follow error:

```
[2020-06-24 05:10:47,058] ERROR WorkerSinkTask{id=test-avro-sink-3-2} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)
[2020-06-24 05:10:47,059] ERROR WorkerSinkTask{id=test-avro-sink-3-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:186)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:492)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:469)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.SchemaBuilderException: Invalid default value
	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:131)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1623)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1500)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1368)
	at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:1080)
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:89)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$2(WorkerSinkTask.java:492)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
	... 13 more
Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema type STRUCT: class java.lang.Long for field: "null"
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:240)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)
	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:129)
	... 22 more
[2020-06-24 05:10:47,060] ERROR WorkerSinkTask{id=test-avro-sink-3-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)
```

Using a consumer I've been able to convert the same messages without seeing the above error, here's a snippet if that helps

```
    avro_deserializer = AvroDeserializer(schema, schema_registry)
    string_deserializer = StringDeserializer('utf_8')

    consumer_conf = {'bootstrap.servers': KAFKA_BROKERS,
                     'key.deserializer': string_deserializer,
                     'value.deserializer': avro_deserializer,
                     'enable.auto.commit': False, 
                     'group.id': 'test_consumer',
                     'auto.offset.reset': offset}

    consumer = DeserializingConsumer(consumer_conf)
```

Is there anyway I can tweak the connector config in kafka connect to ingest the data? I don't think I have the option of changing the avro schema. If I could change the schema what would need to be changed?

**Comment by saumyasuhagiya** [comment]
any update on this? facing same on custom transformer.
