### ISSUE TITLE
S3 Sink Connector is not able to push Avro files

### ISSUE THREAD

**Issue by pablocavalieri** [confluentinc/kafka-connect-storage-cloud#347]
I have an application that sends messages to a kafka topic using String as key and an Avro file as value.
I want to use kafka-connect to read from that kafka topic and push to an S3 bucket.
To do that, I use the io.confluent.connect.s3.S3SinkConnector.
This is my worker configuration:
```
{
  "name": "push-from-kafka-to-s3",
  "config": {
    "connector.class": "io.confluent.connect.s3.S3SinkConnector",
    "tasks.max": "1",
    "topics": "my topic",
    "consumer.override.auto.offset.reset": "earliest",
    "s3.bucket.name": "S3 bucket name",
    "s3.region": "us-east-1",
    "s3.part.size": "5242880",
    "flush.size": "300000",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url": "my schema registry url",
    "storage.class": "io.confluent.connect.s3.storage.S3Storage",
    "format.class": "io.confluent.connect.s3.format.avro.AvroFormat",
    "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
    "locale": "en",
    "timezone": "UTC",
    "topics.dir": "message-recordings-avro-test",
    "path.format": "'date'=YYYY-MM-dd/'hour'=HH",
    "partition.duration.ms": "3600000",
    "rotate.interval.ms": "60000",
    "timestamp.extractor": "Record"
  }
}
```
Looking at the kafka-connectors logs I get this error:
```
[2020-07-21 11:20:35,273] ERROR WorkerSinkTask{id=push-from-kafka-to-s3-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:488)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:465)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic my topic to Avro:
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:114)
        at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:86)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$2(WorkerSinkTask.java:488)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
        ... 13 more
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
```
If I used the `kafka-avro-console-consumer` command from the kafka-connect to read the topic, I can see the messages
`kafka-avro-console-consumer --bootstrap-server kafka broker --consumer-property security.protocol=SSL --property schema.registry.url="my schema registry url" --topic my topic`
Is there some configuration missing in the kafka-connect worker? If I remove the `value.converter` and `key.converter` properties, it works, but the Avro files pushed does not contains the schema

**Comment by ftieben** [comment]
We have the same issue on our side, the key.converter settings seems not to work as intended..

**Comment by pablocavalieri** [comment]
I'm not longer working on that, but the next step from my point of view is start debugging the kafka-connect code.

**Comment by pablocavalieri** [comment]
Closing. The problem seemed to be that, by default, the kafka-recorder worker starts reading from the beginning of the topic, and my topic contained early non avro formatted messages.
To set the worker to read from the earliest message:
`"consumer.override.auto.offset.reset": "earliest"`
