### ISSUE TITLE
«Task already exists in this worker.»

### ISSUE THREAD

**Issue by yazgoo** [confluentinc/kafka-connect-storage-cloud#354]
Hi,

With CP 5.5, and s3 sink, we're getting the following errors when querying status:

```
org.apache.kafka.connect.errors.ConnectException: Task already exists in this worker: s3-rtb_bid_response-sink-50
    at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:422)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1147)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:126)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder$12.call(DistributedHerder.java:1162)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder$12.call(DistributedHerder.java:1158)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by OneCricketeer** [comment]
This appears to be a general Connect exception rather than specific to S3 sink.

Otherwise, would be better to see debug logs of the server
