### ISSUE TITLE
AWS access keys not accessible 

### ISSUE THREAD

**Issue by Shukla-Ankur** [confluentinc/kafka-connect-storage-cloud#370]
Kafka- Apache kafka 2.5.1
Connect- conflucent s3 sink connect v5.5.1

I'm running in distributed mode with command
`
sh bin/connect-distributed.sh connect-distributed.properties
`
while this connects to kafka, connection to s3 fails with error 
`
com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records
`

Full trace:
`
 ERROR WorkerSinkTask{id=s3-sink-connect-titos-test-connector-0-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:187)
org.apache.kafka.connect.errors.ConnectException: com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 6D40C769421C7C27; S3 Extended Request ID: lWzPFp+kARSj4BsjTOl1SpPHxqoSL0Kc/otbndFUc6tDDlOgBLcwxofH3AE+pCP00DpF+42P9xE=), S3 Extended Request ID: lWzPFp+kARSj4BsjTOl1SpPHxqoSL0Kc/otbndFUc6tDDlOgBLcwxofH3AE+pCP00DpF+42P9xE=
        at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:121)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:305)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 6D40C769421C7C27; S3 Extended Request ID: lWzPFp+kARSj4BsjTOl1SpPHxqoSL0Kc/otbndFUc6tDDlOgBLcwxofH3AE+pCP00DpF+42P9xE=), S3 Extended Request ID: lWzPFp+kARSj4BsjTOl1SpPHxqoSL0Kc/otbndFUc6tDDlOgBLcwxofH3AE+pCP00DpF+42P9xE=
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1799)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1383)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1359)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998)
        at com.amazonaws.services.s3.AmazonS3Client.getAcl(AmazonS3Client.java:3912)
        at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1241)
        at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1231)
        at com.amazonaws.services.s3.AmazonS3Client.doesBucketExistV2(AmazonS3Client.java:1369)
        at io.confluent.connect.s3.storage.S3Storage.bucketExists(S3Storage.java:197)
        at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:106)
`
 
running `aws s3 ls` is successful. These values are picked from aws credentials file located at ~/.aws/credentials. However, I have multiple profiles in this, along with a default one.  I did set up the env variables, but still got the same error. In that case, using aws cli required mentioning the profile i.e. `aws s3 ls --profile default` . So I unset the env variables and simply used the vcreds file.

**Comment by catalingavan** [comment]
Subscribing as I have the same problem

**Comment by catalingavan** [comment]
You also need to provide the AWS_SESSION_TOKEN in order to work:

```
version: "3"
services:
    kafka-connect:
        build:
            context: ./kafka-connect
            dockerfile: Dockerfile
        container_name: kafka_connect
        depends_on:
            - kafka
        ports:
            - "8083:8083"
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}

```

**Comment by OneCricketeer** [comment]
All AWS access within the connector follows the same behavior as the AWS JVM SDK

https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
