### ISSUE TITLE
S3 Sink connector stops after few minutes, causes Connect server to hang up (Java process defunct)

### ISSUE THREAD

**Issue by lohisoftware** [confluentinc/kafka-connect-storage-cloud#386]
We have a puzzling problem that I hope someone has ideas how to solve. Have you experienced the same? What could be the issue? Thanks in advance for your help.

We run Kafka in AWS MSK and host connect servers (three instances) by ourselves in distributed mode. We have Kafka topics that already have a lot of messages. Each topic has three partitions. Connect servers are running smoothly with multiple Confluent JDBC sink connectors. 

We add one S3 sink connector. It is able to write files to S3. Connect server still works smoothly. However, as soon as we add a second S3 sink connector Connect server hands immediately. The S3 sink connectors read from different topics, but they do write to the same bucket. We can see that at the time of the hang, both connectors are writing to S3 and committing offsets to Kafka. [UPDATE: Connect server seems to hang also with just one S3 sink connector, that is reading from multiple topics]

Here is a log message when hang happens:

[2021-01-07 17:18:08,980] INFO Files committed to S3. Target commit offset for TOPIC1 is 142310 (io.confluent.connect.s3.TopicPartitionWriter)
[2021-01-07 17:18:09,421] INFO Files committed to S3. Target commit offset for TOPIC2 is 1835 (io.confluent.connect.s3.TopicPartitionWriter)
[2021-01-07 17:18:09,449] INFO Files committed to S3. Target commit offset for TOPIC1 is 142849 (io.confluent.connect.s3.TopicPartitionWriter)
[2021-01-07 17:18:09,828] INFO Files committed to S3. Target commit offset for TOPIC2 is 2469 (io.confluent.connect.s3.TopicPartitionWriter)

and stops here. There are no errors or exceptions in connect server logs when it hangs. The connect server is also not running out of memory at that moment.

When we log into connect servers, we can see that the java process is in "defunct" state. The only way to fix the situation is to restart connect servers and as quickly as possible remove the S3 sink connectors (or otherwise the connect servers get in to defunct state again).

Here are more logs from one S3 sink task:

[2020-12-21 17:06:49,576] INFO [Worker clientId=connect-1, groupId=my_group_id] Joined group at generation 3 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-1-d6356198-ff74-4087-9c78-f679a181bbe5', leaderUrl='http://REDACTED:8083/', offset=485, connectorIds=[MY_S3_SINK, MY_OTHER_S3_SINK], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
[2020-12-21 17:06:50,251] INFO [Worker clientId=connect-1, groupId=my_group_id] Starting task MY_S3_SINK-1 (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
[2020-12-21 17:06:50,253] INFO Creating task MY_S3_SINK-1 (org.apache.kafka.connect.runtime.Worker)
[2020-12-21 17:06:50,254] INFO Instantiated task MY_S3_SINK-1 with version 5.5.2 of type io.confluent.connect.s3.S3SinkTask (org.apache.kafka.connect.runtime.Worker)
[2020-12-21 17:06:50,254] INFO Set up the key converter class org.apache.kafka.connect.storage.StringConverter for task MY_S3_SINK-1 using the connector config (org.apache.kafka.connect.runtime.Worker)
[2020-12-21 17:06:50,254] INFO Set up the value converter class org.apache.kafka.connect.storage.StringConverter for task MY_S3_SINK-1 using the connector config (org.apache.kafka.connect.runtime.Worker)
[2020-12-21 17:06:50,254] INFO Set up the header converter class org.apache.kafka.connect.storage.SimpleHeaderConverter for task MY_S3_SINK-1 using the worker config (org.apache.kafka.connect.runtime.Worker)
	client.id = connector-consumer-MY_S3_SINK-1
[2020-12-21 17:06:50,269] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] Subscribed to topic(s): my_topic (org.apache.kafka.clients.consumer.KafkaConsumer)
[2020-12-21 17:06:51,325] INFO WorkerSinkTask{id=MY_S3_SINK-1} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-12-21 17:06:51,344] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] Cluster ID: REDACTED (org.apache.kafka.clients.Metadata)
[2020-12-21 17:06:51,344] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] Discovered group coordinator REDACTED.amazonaws.com:9092 (id: REDACTED rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-12-21 17:06:51,344] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-12-21 17:06:51,347] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] Join group failed with org.apache.kafka.common.errors.MemberIdRequiredException: The group member needs to have a valid member id before actually entering a consumer group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-12-21 17:06:51,347] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-12-21 17:06:54,346] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-2, groupId=connect-MY_S3_SINK] Finished assignment for group at generation 3: {connector-consumer-MY_S3_SINK-1-4aef5c6d-c32c-4bdf-a535-c47e3c4fa8f6=Assignment(partitions=[my_topic-1]), connector-consumer-MY_S3_SINK-2-948a6292-73d2-47a4-a7ef-33ad029cc100=Assignment(partitions=[my_topic-2]), connector-consumer-MY_S3_SINK-0-05255900-ef77-4f30-8bf0-85cc75ca5705=Assignment(partitions=[my_topic-0])} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-12-21 17:06:54,354] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] Successfully joined group with generation 3 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-12-21 17:06:54,357] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] Adding newly assigned partitions: my_topic-1 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-12-21 17:06:54,358] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] Found no committed offset for partition my_topic-1 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-12-21 17:06:54,368] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] Resetting offset for partition my_topic-1 to offset 0. (org.apache.kafka.clients.consumer.internals.SubscriptionState)
[2020-12-21 17:06:58,610] INFO Stopping task MY_S3_SINK-1 (org.apache.kafka.connect.runtime.Worker)
[2020-12-21 17:06:59,023] INFO WorkerSinkTask{id=MY_S3_SINK-1} Committing offsets synchronously using sequence number 1: {my_topic-1=OffsetAndMetadata{offset=1500, leaderEpoch=null, metadata=''}} (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-12-21 17:06:59,023] INFO WorkerSinkTask{id=MY_S3_SINK-1} Committing offsets synchronously using sequence number 1: {my_topic-1=OffsetAndMetadata{offset=1500, leaderEpoch=null, metadata=''}} (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-12-21 17:06:59,028] ERROR WorkerSinkTask{id=MY_S3_SINK-1} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.common.errors.WakeupException
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:511)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:275)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:212)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:984)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1510)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1458)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.doCommitSync(WorkerSinkTask.java:340)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.doCommit(WorkerSinkTask.java:368)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:439)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:601)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-21 17:06:59,029] ERROR WorkerSinkTask{id=MY_S3_SINK-1} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2020-12-21 17:06:59,029] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] Revoke previously assigned partitions my_topic-1 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-12-21 17:06:59,029] INFO [Consumer clientId=connector-consumer-MY_S3_SINK-1, groupId=connect-MY_S3_SINK] Member connector-consumer-MY_S3_SINK-1-4aef5c6d-c32c-4bdf-a535-c47e3c4fa8f6 sending LeaveGroup request to coordinator REDACTED.amazonaws.com:9092 (id: REDACTED rack: null) due to the consumer is being closed (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-12-21 17:07:03,592] INFO [Worker clientId=connect-1, groupId=my_group_id] Joined group at generation 4 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-1-d6356198-ff74-4087-9c78-f679a181bbe5', leaderUrl='http://REDACTED:8083/', offset=486, connectorIds=connectorIds=[MY_S3_SINK, MY_OTHER_S3_SINK], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder)

Logs end here.

**Comment by lohisoftware** [comment]
Update the bug topic and description with our latest findings.
