### ISSUE TITLE
Parsing issues in JSON 

### ISSUE THREAD

**Issue by Shukla-Ankur** [confluentinc/kafka-connect-storage-cloud#421]
Originally, CDC from MySQL is published using [maxwell](http://maxwells-daemon.io/) to an apache Kafka cluster running v2.2.1. 
These events are read using this S3 sink connector v5.2.1 with confluent Kafka 5.2.1 jars. 
**converters in connect-distributed.properties**
`key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter`

**Connector config**
`{
    "connector.class": "io.confluent.connect.s3.S3SinkConnector",
    "behavior.on.null.values": "ignore",
    "s3.region": "ap-southeast-1",
    "flush.size": "10000",
    "schema.compatibility": "NONE",
    "topics": "audit",
    "tasks.max": "4",
    "s3.part.size": "10485760",
    "timezone": "UTC",
    "locale": "en_US_POSIX",
    "retry.backoff.ms": "100",
    "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
    "partitioner.class": "io.confluent.connect.storage.partitioner.HourlyPartitioner",
    "name": "s3-sink-connector-cdc-events",
    "storage.class": "io.confluent.connect.s3.storage.S3Storage",
    "s3.bucket.name": "audit",
    "timestamp.extractor": "Record",
    "s3.retry.backoff.ms": "100",
    "rotate.schedule.interval.ms": "60000"
    }`

This connector works fine mostly. However, I see some parsing errors 
`task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:484)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Converting byte[] to Kafka Connect data failed due to serialization error:
    at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:344)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$0(WorkerSinkTask.java:484)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
    ... 13 more
Caused by: org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('d' (code 100)): Expected space separating root-level values
 at [Source: (byte[])"3d5b807d-a6c7-43da-bbcc-d40efe9753a7"; line: 1, column: 3]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('d' (code 100)): Expected space separating root-level values
 at [Source: (byte[])"3d5b807d-a6c7-43da-bbcc-d40efe9753a7"; line: 1, column: 3]
    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:638)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._verifyRootSpace(UTF8StreamJsonParser.java:1635)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parsePosNumber(UTF8StreamJsonParser.java:1375)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:830)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:729)
    at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4042)
    at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2571)
    at org.apache.kafka.connect.json.JsonDeserializer.deserialize(JsonDeserializer.java:50)
    at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:342)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$0(WorkerSinkTask.java:484)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:484)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)`

So I updated the connector config and added following also:
`   "errors.log.include.messages": "true",
    "errors.deadletterqueue.context.headers.enable": "true",
    "errors.deadletterqueue.topic.name": "audit_dlq_sink_00",
    "errors.tolerance": "all",
    "errors.log.enable": "true",
`

With this, connector runs and erroneous message is put into DLQ. I checked the message and it was a valid JSON. One of messages in DLQ:
`{
    "type": "table-alter",
    "database": "prod$platform",
    "table": "series",
    "old": {
        "database": "prod$platform",
        "charset": "utf8mb4",
        "table": "series",
        "columns": [
            {
                "type": "varchar",
                "name": "id",
                "charset": "utf8mb4"
            },
            {
                "type": "bigint",
                "name": "created_time",
                "signed": true
            },
            {
                "type": "bigint",
                "name": "updated_time",
                "signed": true
            },
            {
                "type": "bigint",
                "name": "tenant_id",
                "signed": true
            },
            {
                "type": "varchar",
                "name": "global_context_id",
                "charset": "utf8mb4"
            },
            {
                "type": "varchar",
                "name": "auth_id",
                "charset": "utf8mb4"
            },
            {
                "type": "bigint",
                "name": "version",
                "signed": true
            },
            {
                "type": "bigint",
                "name": "series_id",
                "signed": true
            },
            {
                "type": "bigint",
                "name": "company_id",
                "signed": true
            },
            {
                "type": "enum",
                "name": "visibility",
                "enum-values": [
                    "OPEN",
                    "INVITE_ONLY",
                    "SCOPED"
                ]
            },
            {
                "type": "varchar",
                "name": "series_name",
                "charset": "utf8mb4"
            },
            {
                "type": "enum",
                "name": "series_state",
                "enum-values": [
                    "PUBLISHED",
                    "ARCHIVED",
                    "DELETED"
                ]
            },
            {
                "type": "mediumtext",
                "name": "description",
                "charset": "utf8mb4"
            },
            {
                "type": "bigint",
                "name": "event_timestamp",
                "signed": true
            },
            {
                "type": "varchar",
                "name": "search_text",
                "charset": "utf8mb4"
            },
            {
                "type": "bit",
                "name": "f_cdc"
            },
            {
                "type": "enum",
                "name": "action",
                "enum-values": [
                    "UNDEFINED",
                    "ALLOW",
                    "DENY"
                ]
            }
        ],
        "primary-key": [
            "tenant_id",
            "series_id"
        ]
    },
    "def": {
        "database": "prod$platform",
        "charset": "utf8mb4",
        "table": "series",
        "columns": [
            {
                "type": "varchar",
                "name": "id",
                "charset": "utf8mb4"
            },
            {
                "type": "bigint",
                "name": "created_time",
                "signed": true
            },
            {
                "type": "bigint",
                "name": "updated_time",
                "signed": true
            },
            {
                "type": "bigint",
                "name": "tenant_id",
                "signed": true
            },
            {
                "type": "varchar",
                "name": "global_context_id",
                "charset": "utf8mb4"
            },
            {
                "type": "varchar",
                "name": "auth_id",
                "charset": "utf8mb4"
            },
            {
                "type": "bigint",
                "name": "version",
                "signed": true
            },
            {
                "type": "bigint",
                "name": "series_id",
                "signed": true
            },
            {
                "type": "bigint",
                "name": "company_id",
                "signed": true
            },
            {
                "type": "enum",
                "name": "visibility",
                "enum-values": [
                    "OPEN",
                    "INVITE_ONLY",
                    "SCOPED"
                ]
            },
            {
                "type": "varchar",
                "name": "series_name",
                "charset": "utf8mb4"
            },
            {
                "type": "enum",
                "name": "series_state",
                "enum-values": [
                    "PUBLISHED",
                    "ARCHIVED",
                    "DELETED"
                ]
            },
            {
                "type": "mediumtext",
                "name": "description",
                "charset": "utf8mb4"
            },
            {
                "type": "bigint",
                "name": "event_timestamp",
                "signed": true
            },
            {
                "type": "varchar",
                "name": "search_text",
                "charset": "utf8mb4"
            },
            {
                "type": "bit",
                "name": "f_cdc"
            },
            {
                "type": "enum",
                "name": "action",
                "enum-values": [
                    "UNDEFINED",
                    "ALLOW",
                    "DENY"
                ]
            },
            {
                "type": "json",
                "name": "rules"
            }
        ],
        "primary-key": [
            "tenant_id",
            "series_id"
        ]
    },
    "ts": 1620885102000,
    "sql": "ALTER TABLE series ADD COLUMN rules JSON NULL"
}`

So I had following questions:
1. for a valid JSON, why parsing would fail?
2. In DLQ, only message is going and not the error log or reason why parsing failed.
3. For key, does using a JSON or string converter make any difference? Can I instead use 'key.converter=org.apache.kafka.connect.storage.StringConverter

**Comment by OneCricketeer** [comment]
This error seems more suited for the Apache Kafka JIRA because the error comes from that Converter, and not the S3 Sink
