### ISSUE TITLE
Invocation Target Exception

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/kafka-connect-storage-cloud#43]
Getting this on Confluent 3.2.0 kafka connect image. Any idea what could be wrong?

```
[2017-05-08 07:03:00,831] ERROR Task s3-sink-test-1-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: java.lang.reflect.InvocationTargetException
	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:47)
	at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:94)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:231)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:145)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:45)
	... 10 more
Caused by: java.lang.NoSuchMethodError: com.amazonaws.ClientConfiguration.withUserAgentPrefix(Ljava/lang/String;)Lcom/amazonaws/ClientConfiguration;
	at io.confluent.connect.s3.storage.S3Storage.newS3Client(S3Storage.java:63)
	at io.confluent.connect.s3.storage.S3Storage.<init>(S3Storage.java:59)
	... 15 more
```

My config:

```
name=s3-sink-test-1
connector.class=io.confluent.connect.s3.S3SinkConnector
tasks.max=3
topics=mytopic

s3.bucket.name=my-kafka-connect-s3-dev
s3.region=ap-southeast-2
s3.part.size=5242880
flush.size=100

storage.class=io.confluent.connect.s3.storage.S3Storage
format.class=io.confluent.connect.s3.format.avro.AvroFormat
topics.dir=topics

schema.generator.class=io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator
partitioner.class=io.confluent.connect.storage.partitioner.TimeBasedPartitioner

schema.compatibility=NONE
partition.duration.ms=30000
path.format=path.format='year'=YYYY/'month'=MM/'day'=dd/'hour'=HH/
```

**Comment by kkonstantine** [comment]
I'm guessing that an older version of the AWS sdk is encountered first in your classpath. Maybe it's being imported as a dependency by another package. Are s3 connector's packages and deps first in your classpath?

**Comment by simplesteph** [comment]
@kkonstantine you were right. Can't wait for your KIP to get through.

**Comment by warsameahmed** [comment]
Hello, @simplesteph I'm having the same issue. however I only get the error when I run kafka connect source with kafka connect sink. I was starting to suspect the issues was related to the classpath, because I noticed Class path contains multiple SLF4J bindings.

SLF4J: Found binding in [jar:file:/usr/local/share/git/kafka-connect-twitter/target/kafka-connect-twitter-0.1-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/share/confluent-3.2.0/share/java/kafka-serde-tools/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/share/confluent-3.2.0/share/java/kafka-connect-elasticsearch/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/share/confluent-3.2.0/share/java/kafka-connect-hdfs/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/share/confluent-3.2.0/share/java/kafka-connect-s3/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/share/confluent-3.2.0/share/java/kafka-connect-storage-common/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/share/confluent-3.2.0/share/java/kafka/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

How did you resolve the class path issue?

**Comment by simplesteph** [comment]
I had some duplicate dependencies with different versions, just make sure you don't include those in your connect cluster, and you should be good. Or make sure all your connectors are using the same dependencies versions. Or create as many clusters as you will run connector classes. @kkonstantine is working on solving that problem from a framework perspective, and hopefully his work will make it into Kafka 0.11.0.0

**Comment by warsameahmed** [comment]
Thanks that worked.
