### ISSUE TITLE
No indication on which message crash the connector

### ISSUE THREAD

**Issue by shlomi-viz** [confluentinc/kafka-connect-storage-cloud#430]
Hey,

I'm running the S3 connector to move data written by `debezium` into S3. In some cases I'm getting the following error 
```bash
Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:614)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: Array contains a null element at 0
Set parquet.avro.write-old-list-structure=false to turn on support for arrays with null elements.
	at org.apache.parquet.avro.AvroWriteSupport$TwoLevelListWriter.writeCollection(AvroWriteSupport.java:556)
	at org.apache.parquet.avro.AvroWriteSupport$ListWriter.writeList(AvroWriteSupport.java:397)
	at org.apache.parquet.avro.AvroWriteSupport.writeValueWithoutConversion(AvroWriteSupport.java:355)
	at org.apache.parquet.avro.AvroWriteSupport.writeValue(AvroWriteSupport.java:278)
	at org.apache.parquet.avro.AvroWriteSupport.writeRecordFields(AvroWriteSupport.java:191)
	at org.apache.parquet.avro.AvroWriteSupport.writeRecord(AvroWriteSupport.java:173)
	at org.apache.parquet.avro.AvroWriteSupport.writeValueWithoutConversion(AvroWriteSupport.java:349)
	at org.apache.parquet.avro.AvroWriteSupport.writeValue(AvroWriteSupport.java:278)
	at org.apache.parquet.avro.AvroWriteSupport.writeRecordFields(AvroWriteSupport.java:191)
	at org.apache.parquet.avro.AvroWriteSupport.write(AvroWriteSupport.java:165)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:128)
	at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:301)
	at io.confluent.connect.s3.format.parquet.ParquetRecordWriterProvider$1.write(ParquetRecordWriterProvider.java:93)
	at io.confluent.connect.s3.format.KeyValueHeaderRecordWriterProvider$1.write(KeyValueHeaderRecordWriterProvider.java:105)
	at io.confluent.connect.s3.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:532)
	at io.confluent.connect.s3.TopicPartitionWriter.checkRotationOrAppend(TopicPartitionWriter.java:302)
	at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:245)
	at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:196)
	at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:234)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
	... 10 more
```

note that there is no way to know on which message has the `Array contains a null element at 0`. I have tried to run it in DEBUG mode but still didn't got more information. Looking at the logs before this error, I can see the last offset that was committed, but my connector is writing 10K or 1H messages each time, so I need to pull all of them and take a look, this is very inefficient and time consuming. 

This is the config I'm using:
```JSON
            "name": "s3-sink-12",
            "connector.class": "io.confluent.connect.s3.S3SinkConnector",
            "flush.size": "10000",
            "format.class": "io.confluent.connect.s3.format.parquet.ParquetFormat",
            "locale": "US",
            "partition.duration.ms": "31556952000",
            "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
            "path.format": "'year'=YYYY/",
            "rotate.schedule.interval.ms": "3600000",
            "s3.bucket.name": "bucket_name",
            "s3.region": "eu-west-1",
            "storage.class": "io.confluent.connect.s3.storage.S3Storage",
            "tasks.max": "1",
            "timezone": "UTC",
            "topics.dir": "db_data_12",
            "topics": "topic_1,topic_2,topic_3",
            "errors.tolerance": "all",
            "errors.deadletterqueue.topic.name":"dlq_s3_sink_12",
            "errors.log.enable": true,
            "errors.log.include.messages": true,
            "transforms": "AddOrderData",
            "transforms.AddOrderData.type": "org.apache.kafka.connect.transforms.InsertField$Value",
            "transforms.AddOrderData.offset.field": "kafka_offset",
            "behavior.on.null.values": "ignore"
```

I saw this issue https://github.com/confluentinc/kafka-connect-storage-cloud/issues/339, but didn't understand how and what I need to change so it will not fail on Null in Array. 

What is the best way to find the offset of the "bad" message? and way doesn't it goes to the DLQ?

Thanks

**Comment by OneCricketeer** [comment]
You can find the message by looking at the consumer group, and seeing what offset is committed

```
kafka-consumer-groups ... --describe--group  connect-s3-sink-12
```

Then you can use console-consumer from `--topic T --offset X --partition Y --max-messages=1`

**Comment by shlomi-viz** [comment]
Thanks for info, but I don't think this will help.
The `S3` task is processing many messages each time. For example if my "bad" message is at `offset=3030` and I set `flush.size=1000` and my last committed offset is `3000`, the task will try to process message 3000 - 4000 and will fail without updating the offset to 3029. So I will need to look at all the messages in 3000-4000. Am I missing anything?

**Comment by OneCricketeer** [comment]
It's been a while since I've managed connect, but I thought it flushed the pending file when an error was encountered. If that's not the case, then you are correct

**Comment by dragondgold** [comment]
@shlomi-viz did you find why the messages are not moved to the DLQ in these cases?
