### ISSUE TITLE
Converting byte[] to Kafka Connect data failed due to serialization error of topic connect-topic1

### ISSUE THREAD

**Issue by Utkarsh-0211** [confluentinc/kafka-connect-storage-cloud#506]
Even though I'm passing the right schema registry and the converter class I'm still getting this error

```
2022-04-11 11:47:20,038 ERROR WorkerSinkTask{id=databus-sink-connector1-0} Error converting message value in topic 'connect-topic1' partition 0 at offset 1 and timestamp 1649677639879: Converting byte[] to Kafka Connect data failed due to serialization error of topic connect-topic1:  (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-databus-sink-connector1-0]
org.apache.kafka.connect.errors.DataException: Converting byte[] to Kafka Connect data failed due to serialization error of topic connect-topic1: 
	at io.confluent.connect.json.JsonSchemaConverter.toConnectData(JsonSchemaConverter.java:119)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:540)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$2(WorkerSinkTask.java:496)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:496)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:473)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:328)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing JSON message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
```
my connector config is:
```
    flush.size:                                      1
    format.class:                                  io.confluent.connect.s3.format.json.JsonFormat
    key.converter:                                org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable:    false
    s3.bucket.name:                            bucket1
    schema.compatibility:                   NONE
    storage.class:                                 io.confluent.connect.s3.storage.S3Storage
    store.url:                                         xxxx
    topics:                                             connect-topic1
    value.converter:                             io.confluent.connect.json.JsonSchemaConverter
    value.converter.schemas.enable:   true
    value.converter.schema.registry.url: xxx
    errors.tolerance:                            all 
    errors.deadletterqueue.topic.name: dead-connect-topic1

```
message I'm passing in the topic : {"f1": "value1-j"}

**Comment by OneCricketeer** [comment]
> message I'm passing in the topic : {"f1": "value1-j"

That doesn't have a json schema.

How exactly are you sending it?
