### ISSUE TITLE
S3 Sink fails if the path doesn't exists

### ISSUE THREAD

**Issue by amit-c1x** [confluentinc/kafka-connect-storage-cloud#61]
IMO, It should create the path if it doesn't exists

**Comment by kkonstantine** [comment]
@amit-c1x are you referring to the bucket?

**Comment by amit-c1x** [comment]
@kkonstantine I am referring to the s3 bucket along with keys. For example the complete path is s3://develop/phase1. The bucket ```develop``` exists but the key ```phase``` doesn't. In this scenario, the connector fails with the exception:

```
[2017-06-28 08:58:57,349] ERROR Task s3-connector-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
org.apache.kafka.connect.errors.DataException: No-existent S3 bucket: develop/phase1
        at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:96)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:231)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:145)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by amit-c1x** [comment]
@kkonstantine  my bad, I was passing the complete path in ```s3.bucket``` field. I did not see there was a ```topics.dir``` config too.
