### ISSUE TITLE
confluent-3.2.2 kafka-connect-s3 

### ISSUE THREAD

**Issue by warsameahmed** [confluentinc/kafka-connect-storage-cloud#67]
Since upgrading to 3.2.2 in order to use the TimeBasedPartitioner, I'm no longer able to start connect-standalone passing the source and sink properties files. 

I'm using this Kafka Connect for Twitter. I've done maven clean build and updated the dependencies to confluent 3.2.2 and kafaka to 10.2.1. 
https://github.com/Eneco/kafka-connect-twitter

Here are the properties in pom file:

<java.version>1.8</java.version>
<scala.version>2.11.7</scala.version>
<confluent.version>3.2.2</confluent.version>
<kafka.version>0.10.2.1</kafka.version>
<hosebird.version>2.2.0</hosebird.version>
<avro.version>1.7.7</avro.version>
<jsr305.version>1.3.9</jsr305.version>
<mockito.version>1.10.19</mockito.version>
<scalatest.version>3.0.0-M1</scalatest.version>
<guava.version>19.0</guava.version>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<confluent.maven.repo>http://packages.confluent.io/maven/</confluent.maven.repo>
<cloudera.maven.repo>https://repository.cloudera.com/artifactory/cloudera-repos</cloudera.maven.repo>

There are dependencies collisions with 3.2.2 that I can't identify.  Can you please let me know what the valid dependencies should be for 3.2.2

**Comment by warsameahmed** [comment]
Here is the error I'm getting when I start connect standalone with source and s3 sink.

[2017-07-11 13:22:57,559] INFO New connection executed: KafkaConnectTwitterSource, endpoint: /1.1/statuses/filter.json?delimited=length (com.twitter.hbc.httpclient.BasicClient:95)
[2017-07-11 13:22:57,560] INFO Source task WorkerSourceTask{id=twitter-source-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:142)
[2017-07-11 13:22:57,605] INFO Kafka version : 0.10.2.1-cp2 (org.apache.kafka.common.utils.AppInfoParser:83)
[2017-07-11 13:22:57,605] INFO Kafka commitId : 3d1ebcd51ecc4d13 (org.apache.kafka.common.utils.AppInfoParser:84)
[2017-07-11 13:22:57,608] INFO Created connector s3-sink (org.apache.kafka.connect.cli.ConnectStandalone:90)
[2017-07-11 13:22:57,610] INFO S3SinkConnectorConfig values: 
	filename.offset.zero.pad.width = 10
	flush.size = 3
	format.class = class io.confluent.connect.s3.format.json.JsonFormat
	retry.backoff.ms = 5000
	rotate.interval.ms = -1
	rotate.schedule.interval.ms = -1
	s3.bucket.name = dev-kafka
	s3.credentials.provider.class = class com.amazonaws.auth.DefaultAWSCredentialsProviderChain
	s3.part.size = 5242880
	s3.region = ca-central-1
	s3.ssea.name = 
	s3.wan.mode = false
	schema.cache.size = 1000
	shutdown.timeout.ms = 3000
 (io.confluent.connect.s3.S3SinkConnectorConfig:180)
[2017-07-11 13:22:57,611] INFO StorageCommonConfig values: 
	directory.delim = /
	file.delim = +
	storage.class = class io.confluent.connect.s3.storage.S3Storage
	store.url = null
	topics.dir = topics
 (io.confluent.connect.storage.common.StorageCommonConfig:180)
[2017-07-11 13:22:57,611] INFO HiveConfig values: 
	hive.conf.dir = 
	hive.database = default
	hive.home = 
	hive.integration = false
	hive.metastore.uris = 
	schema.compatibility = NONE
 (io.confluent.connect.storage.hive.HiveConfig:180)
[2017-07-11 13:22:57,612] INFO PartitionerConfig values: 
	locale = en
	partition.duration.ms = 5
	partition.field.name = 
	partitioner.class = class io.confluent.connect.storage.partitioner.TimeBasedPartitioner
	path.format = 'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH/
	schema.generator.class = class io.confluent.connect.storage.hive.schema.TimeBasedSchemaGenerator
	timestamp.extractor = Wallclock
	timestamp.field = timestamp
	timezone = EST
 (io.confluent.connect.storage.partitioner.PartitionerConfig:180)
[2017-07-11 13:22:57,705] INFO KafkaConnectTwitterSource Establishing a connection (com.twitter.hbc.httpclient.ClientBase:173)
[2017-07-11 13:22:57,803] ERROR Task s3-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
org.apache.kafka.connect.errors.ConnectException: java.lang.reflect.InvocationTargetException
	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:47)
	at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:94)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:231)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:145)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:45)
	... 10 more
Caused by: java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:87)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:65)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:58)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:51)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:39)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:319)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:303)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:173)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:645)
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:31)
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:28)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:60)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:26)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:38)
	at io.confluent.connect.s3.storage.S3Storage.newS3Client(S3Storage.java:81)
	at io.confluent.connect.s3.storage.S3Storage.<init>(S3Storage.java:59)
	... 15 more
[2017-07-11 13:22:57,805] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:142)
[2017-07-11 13:22:58,446] INFO KafkaConnectTwitterSource Processing connection data (com.twitter.hbc.httpclient.ClientBase:240)

**Comment by ewencp** [comment]
Given `org.apache.http.conn.ssl.SSLConnectionSocketFactory` is where the call happens, my guess would be that it's a conflict with the apache http libraries. I think it's pulled in indirectly in the connector, but Kafka has httpclient, httpcore, and httpmime jars that ship with it.

We added [classloader isolation](https://cwiki.apache.org/confluence/display/KAFKA/KIP-146+-+Classloading+Isolation+in+Connect) in Kafka 0.11 in order to address these types of conflicts, and Confluent 3.3 will be out soon with that support. You might try that in order to avoid this conflict.

**Comment by warsameahmed** [comment]
Thanks for the quick reply @ewencp. This is greatly needed. It's such a pain getting all these various big data apache tools piped together. Architecting something like the classloader isolation is such a great idea to overcome the class conflict that comes from all the various platforms . Looking forward to 3.3 and 0.11

**Comment by kkonstantine** [comment]
Let us know if you are still experiencing the issue when using the `plugin.path` property in Kafka that is also shipped now with 3.3.0 or you found a workaround for this specific conflict in 3.2.x. In either case, if this is resolved, we could go ahead and close this ticket.

**Comment by kkonstantine** [comment]
It's been a while since we discussed this. Closing.
