### ISSUE TITLE
Convert to Parquet S3 Sink problems

### ISSUE THREAD

**Issue by davira** [confluentinc/kafka-connect-storage-cloud#677]
Hi there, 

When trying to convert an avro to parquet and dump to S3 files, I have encounter the following error (see below).

After spending way too much time down the rabitt hole, I found a possible cause:
https://stackoverflow.com/questions/68698325/confluent-kafka-s3-sink-connector-throws-java-lang-noclassdeffounderror-com-go

But I am not sure. Can someone help?

**Configuration file:**
![image](https://github.com/confluentinc/kafka-connect-storage-cloud/assets/8401868/f2cafe04-676b-4d31-9670-0824caf644c6)

**Error**
[2023-08-23 15:32:49,415] ERROR [hwc_obs-sink|task-0] WorkerSinkTask{id=hwc_obs-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: org/apache/hadoop/thirdparty/com/google/common/collect/Interners (org.apache.kafka.connect.runtime.WorkerSinkTask:616)
java.lang.NoClassDefFoundError: org/apache/hadoop/thirdparty/com/google/common/collect/Interners
        at org.apache.hadoop.util.StringInterner.<clinit>(StringInterner.java:40)
        at org.apache.hadoop.conf.Configuration$Parser.handleEndElement(Configuration.java:3335)
        at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3417)
        at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3191)
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3084)
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:3045)
        at org.apache.hadoop.conf.Configuration.loadProps(Configuration.java:2923)
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2905)
        at org.apache.hadoop.conf.Configuration.get(Configuration.java:1247)
        at org.apache.hadoop.conf.Configuration.getTrimmed(Configuration.java:1301)
        at org.apache.hadoop.conf.Configuration.getBoolean(Configuration.java:1708)
        at org.apache.parquet.avro.AvroSchemaConverter.<init>(AvroSchemaConverter.java:90)
        at org.apache.parquet.avro.AvroParquetWriter.writeSupport(AvroParquetWriter.java:149)
        at org.apache.parquet.avro.AvroParquetWriter.access$200(AvroParquetWriter.java:36)
        at org.apache.parquet.avro.AvroParquetWriter$Builder.getWriteSupport(AvroParquetWriter.java:182)
        at org.apache.parquet.hadoop.ParquetWriter$Builder.build(ParquetWriter.java:563)
        at io.confluent.connect.s3.format.parquet.ParquetRecordWriterProvider$1.write(ParquetRecordWriterProvider.java:102)
        at io.confluent.connect.s3.format.S3RetriableRecordWriter.write(S3RetriableRecordWriter.java:51)
        at io.confluent.connect.s3.format.KeyValueHeaderRecordWriterProvider$1.write(KeyValueHeaderRecordWriterProvider.java:114)
        at io.confluent.connect.s3.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:592)
        at io.confluent.connect.s3.TopicPartitionWriter.checkRotationOrAppend(TopicPartitionWriter.java:327)
        at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:267)
        at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:218)
        at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:244)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:204)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.thirdparty.com.google.common.collect.Interners
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:136)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 36 more
[2023-08-23 15:32:49,417] ERROR [hwc_obs-sink|task-0] WorkerSinkTask{id=hwc_obs-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:212)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:618)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:204)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/thirdparty/com/google/common/collect/Interners
        at org.apache.hadoop.util.StringInterner.<clinit>(StringInterner.java:40)
        at org.apache.hadoop.conf.Configuration$Parser.handleEndElement(Configuration.java:3335)
        at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3417)
        at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3191)
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3084)
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:3045)
        at org.apache.hadoop.conf.Configuration.loadProps(Configuration.java:2923)
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2905)
        at org.apache.hadoop.conf.Configuration.get(Configuration.java:1247)
        at org.apache.hadoop.conf.Configuration.getTrimmed(Configuration.java:1301)
        at org.apache.hadoop.conf.Configuration.getBoolean(Configuration.java:1708)
        at org.apache.parquet.avro.AvroSchemaConverter.<init>(AvroSchemaConverter.java:90)
        at org.apache.parquet.avro.AvroParquetWriter.writeSupport(AvroParquetWriter.java:149)
        at org.apache.parquet.avro.AvroParquetWriter.access$200(AvroParquetWriter.java:36)
        at org.apache.parquet.avro.AvroParquetWriter$Builder.getWriteSupport(AvroParquetWriter.java:182)
        at org.apache.parquet.hadoop.ParquetWriter$Builder.build(ParquetWriter.java:563)
        at io.confluent.connect.s3.format.parquet.ParquetRecordWriterProvider$1.write(ParquetRecordWriterProvider.java:102)
        at io.confluent.connect.s3.format.S3RetriableRecordWriter.write(S3RetriableRecordWriter.java:51)
        at io.confluent.connect.s3.format.KeyValueHeaderRecordWriterProvider$1.write(KeyValueHeaderRecordWriterProvider.java:114)
        at io.confluent.connect.s3.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:592)
        at io.confluent.connect.s3.TopicPartitionWriter.checkRotationOrAppend(TopicPartitionWriter.java:327)
        at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:267)
        at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:218)
        at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:244)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        ... 11 more
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.thirdparty.com.google.common.collect.Interners
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:136)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 36 more

**Comment by davira** [comment]
Seems adding

**Comment by davira** [comment]
Seems by adding this library will work:

https://jar-download.com/artifacts/org.apache.hadoop.thirdparty

**Comment by BDeus** [comment]
Same here .
We previously been in 10.5.1.
When upgrade to 10.5.4 this error appears.
Probably related to the upgrade of kafka-connect-storage-common

**Comment by diseku** [comment]
same issue after the upgrade to 10.5.4

**Comment by frankgrimes97** [comment]
Can someone confirm if it's now fixed in `10.5.5`?
https://docs.confluent.io/kafka-connectors/s3-sink/current/changelog.html#version-10-5-5
https://github.com/confluentinc/kafka-connect-storage-cloud/pull/680

FWIW, we're planning to upgrade soon and noticed this open issue. (we emit Parquet currently on an older connector release)

**Comment by vdesabou** [comment]
@frankgrimes97 Yes this is fixed starting from 10.5.5

It impacted version 10.5.3 and 10.5.4
