### ISSUE TITLE
connector is not interoperable with other s3-compliant cloud storage providers

### ISSUE THREAD

**Issue by mhmcdonald** [confluentinc/kafka-connect-storage-cloud#747]
According to [the S3 Sink documentation](https://docs.confluent.io/kafka-connectors/s3-sink/current/overview.html#using-non-aws-storage-providers), the connector is supposed to be able to support cloud storage providers that have a compatible API. I’m running into an error when trying to use a GCS bucket with the S3 Sink Connector.

To do this, I’m using a GCS bucket with a HMAC Key. I’ve tested the GCS bucket using this HMAC Key and can confirm that using the AWS CLI, I’m able to put objects into the GCS bucket. So I’m certain that IAM permissions are correct and that the HMAC key is valid.

Below is representative of my connector configuration:
```
{
“topics”: “gcs-test-topic”,
“path.format”: “‘year’=YYYY/‘month’=MM/‘day’=dd/‘hour’=HH”,
“partitioner.class”: “io.confluent.connect.storage.partitioner.TimeBasedPartitioner”,
“storage.class”: “io.confluent.connect.s3.storage.S3Storage”,
“connector.class”: “io.confluent.connect.s3.S3SinkConnector”,
“s3.bucket.name”: “my-gcs-bucket-test-s3-sink-example”,
“partition.duration.ms”: “300000”,
“s3.part.size”: “8388608”,
“aws.access.key.id”: “< HMAC access key id >”,
“aws.secret.access.key”: “< HMAC Secret Key >”
“errors.log.enable”: “true”,
“name”: “gcs-s3-sink-connector”,
“format.class”: “io.confluent.connect.s3.format.json.JsonFormat”,
“s3.region”: “auto”,
“store.url”: “https://storage.googleapis.com/”,
“timezone”: “UTC”,
“tasks.max”: “3”,
“flush.size”: “6000”,
“locale”: “US”,
“rotate.interval.ms”: “240000”,
“timestamp.extractor”: “Record”,
“errors.log.include.messages”: “true”,
“rotate.schedule.interval.ms”: “240000”,
“errors.tolerance”: “all”,
“s3.compression.type”: “gzip”,
}
```
this is the error that I’m encountering:

```
org.apache.kafka.connect.errors.ConnectException: com.amazonaws.services.s3.model.AmazonS3Exception: Invalid argument. (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:142)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:312)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:187)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Invalid argument. (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5520)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5467)
	at com.amazonaws.services.s3.AmazonS3Client.getAcl(AmazonS3Client.java:4113)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1308)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1298)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExistV2(AmazonS3Client.java:1436)
	at io.confluent.connect.s3.storage.S3Storage.bucketExists(S3Storage.java:186)
	at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:114)
	... 8 more
```

The connector is using a method from the AWS java sdk called `doesBucketExistV2` which is where my error is coming from. You can see it [in use here](https://github.com/confluentinc/kafka-connect-storage-cloud/blob/fd9c87fe1d1ce8299ae68453176eb7d7126bc405/kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3Storage.java#L186). According [to this issue](https://github.com/aws/aws-sdk-java/issues/2889), that method breaks interoperability with other S3 compatible APIs. 

It should be possible to check if the BucketExists [using the HeadBucket operation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html) rather than `doesBucketExistV2`.

**Comment by mhmcdonald** [comment]
GCS buckets are interoperable with this connector. They requires the use of ACLs rather than IAM
