### ISSUE TITLE
S3 Connector preCommit() Null Pointer exception

### ISSUE THREAD

**Issue by ismail261** [confluentinc/kafka-connect-storage-cloud#76]
I got this error after i added the property in s3 connector "schedule.rotate.interval.ms"=5000.
i am using confluent 3.2.0.

INFO Revoking previously assigned partitions [] for group connect-kafka-s3-client-events (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:393)
[2017-07-26 14:08:06,483] INFO (Re-)joining group connect-kafka-s3-client-events (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:407)
[2017-07-26 14:08:07,174] INFO Successfully joined group connect-kafka-s3-client-events with generation 385 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:375)
[2017-07-26 14:08:07,182] INFO Setting newly assigned partitions [devauto.reliance.client.v1.test-0] for group connect-kafka-s3-client-events (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:252)
[2017-07-26 14:08:07,332] INFO Fetch offset 70 is out of range for partition devauto.reliance.client.v1.test-0, resetting offset (org.apache.kafka.clients.consumer.internals.Fetcher:820)
[2017-07-26 14:08:25,423] INFO Reflections took 26578 ms to scan 590 urls, producing 14875 keys and 101872 values  (org.reflections.Reflections:229)
[2017-07-26 14:09:02,326] WARN {} Offset commit failed during close (org.apache.kafka.connect.runtime.WorkerSinkTask:302)
[2017-07-26 14:09:02,328] ERROR Commit of WorkerSinkTask{id=kafka-s3-client-events-0} offsets threw an unexpected exception:  (org.apache.kafka.connect.runtime.WorkerSinkTask:204)
java.lang.NullPointerException
	at io.confluent.connect.s3.S3SinkTask.preCommit(S3SinkTask.java:176)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:299)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:480)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:152)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-07-26 14:09:02,331] ERROR Task kafka-s3-client-events-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
java.lang.NullPointerException
	at io.confluent.connect.s3.S3SinkTask.close(S3SinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:317)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:480)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:152)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-07-26 14:09:02,332] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:142)

**Comment by kkonstantine** [comment]
To use `schedule.rotate.interval.ms` with any partitioner please upgrade to 3.3.0 and see if you get the same exception.

**Comment by ismail261** [comment]
I tried using 3.3.0 just for kafka-connect-s3 but i still get that same error

![screenshot from 2017-08-07 12-24-18](https://user-images.githubusercontent.com/11082044/29035988-8fbb6908-7b6b-11e7-9f6b-09ea1ead350b.png)
![screenshot from 2017-08-07 12-24-45](https://user-images.githubusercontent.com/11082044/29035989-8fbc8b08-7b6b-11e7-8ba5-104c431b42a8.png)

**Comment by ismail261** [comment]
I also tried to use property schedule.interval.ms and that also failed with the following exception:

![screenshot from 2017-08-07 12-36-27](https://user-images.githubusercontent.com/11082044/29036381-39400f1e-7b6d-11e7-9f26-15ccabcbe2ff.png)

**Comment by ewencp** [comment]
What version of Kafka are you on and what timestamp setting does the the topic you're consuming from have? Just based on where the NPE is coming from, it looks like it *might* be a `null` timestamp causing the crash.

**Comment by ismail261** [comment]
@ewencp 

Kafka version that is installed on kafka brokers is 0.10.1.0-cp2.
But the connectors that are getting packaged and deployed with confluent library is 3.3.0 so they are using 0.11.0.0-cp1.

I don't understand exactly what do you mean by timestamp setting. S3 connector is using field partitioner and i don't have any timestamp column in that message which is being consumed.

I thought this property rotate.interval.ms would be invoked every specific interval and will commit if there are any files. As soon as connector is started, it would commit files according to flush size specified. And after that whatever is reached first, flush size or time interval it will commit there after. Isn't that right? How is this related to timestamp setting?

**Comment by ewencp** [comment]
@ismail261 I meant the `log.message.timestamp.type` setting on the broker but it seems unrelated.

The reason you're seeing the error is that the `rotate.interval.ms` setting is meant to work with the timestamps in messages, but currently only works with `TimeBasedPartitioner` implementations. I think you want the `rotate.schedule.interval.ms` which will always be based on wall-clock time.

**Comment by ismail261** [comment]
@ewencp I have tried with both. When i try to use rotate.schedule.interval.ms i get the following error which is null pointer exception on S3SinkTask.preCommit method.

![screenshot from 2017-08-07 12-24-45](https://user-images.githubusercontent.com/11082044/29083443-c14ffada-7c36-11e7-90fe-1c3d906bbc00.png)

**Comment by ismail261** [comment]
@ewencp I thought this might be happening as i am using kafka 10 server. But i tested this locally with zookeeper, kafka, schema registry and kafka connect all using 3.3.0 image and it still gives me null pointer exception.

**Comment by tomaszj** [comment]
Hi folks, I'm using `rotate.schedule.interval.ms` as well with `DefaultPartitioner` in 4.0.0 version and I get the same NullPointerExceptions.

Please note that without that setting, the S3 Connector seems to be working fine.

Here's the config:

```
{
  "name": "some-name",
  "config": {
    "connector.class": "io.confluent.connect.s3.S3SinkConnector",
    "tasks.max": "1",
    "topics": "some-topic",
    "s3.region": "eu-west-1",
    "s3.bucket.name": "some-bucket",
    "s3.ssea.name": "aws:kms",
    "s3.part.size": "5242880",
    "topics.dir": "some-folder",
    "flush.size": "100",
    "rotate.schedule.interval.ms": "10000",
    "storage.class": "io.confluent.connect.s3.storage.S3Storage",
    "format.class": "io.confluent.connect.s3.format.avro.AvroFormat",
    "schema.generator.class": "io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator",
    "partitioner.class": "io.confluent.connect.storage.partitioner.DefaultPartitioner",
    "schema.compatibility": "NONE",
    "name": "some-name"
  }
}
```

And here's the relevant part of the log:

```[2018-01-04 13:28:55,375] ERROR WorkerSinkTask{id=some-name-0} Commit of offsets threw an unexpected exception for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.NullPointerException
at io.confluent.connect.s3.S3SinkTask.preCommit(S3SinkTask.java:210)
at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:345)
at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:547)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:170)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
[2018-01-04 13:28:55,377] ERROR WorkerSinkTask{id=some-name-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.NullPointerException
at io.confluent.connect.s3.S3SinkTask.close(S3SinkTask.java:223)
at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:363)
at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:547)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:170)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by kkonstantine** [comment]
@tomaszj are these similar exceptions the only exceptions you are getting? They don't seem to be the root cause of the issue because they happen when the sink task executing this connector stops, possibly in an unexpected way. 

Have you tried turning on DEBUG or TRACE logging? Is this reproducible and is this happening with the connector running on a single node with 1 task and no other connectors, or the scenario is different?

**Comment by tomaszj** [comment]
@kkonstantine when pasting, I missed two lines. I turned on the DEBUG logging, but got the same results (no extra exceptions or entries suggesting things going awry). Here are these:
```
[2018-01-05 18:03:11,168] WARN WorkerSinkTask{id=some-connector-0} Offset commit failed during close (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2018-01-05 18:03:11,169] ERROR WorkerSinkTask{id=some-connector-0} Commit of offsets threw an unexpected exception for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask)
```

Currently there are 3 nodes of Kafka Connect. Not sure about the tasks, but you could probably tell that from the config above. The source Kafka topic has two partitions. No other connectors were running.

**Comment by drewdahlke** [comment]
I hit the same thing with 4.0.0-2.11. Single node, single task, default partitioner, same stack trace. It works as soon as I remove rotate.schedule.interval.ms from the config. It happens immediately when updating the config so it's pretty easy to reproduce.

**Comment by mleveck** [comment]
I'm getting The same error, right after deploy a connector config.  Happens immediately with `rotate.schedule.interval.ms`, and goes away when the setting is omitted.  Here is the debug trace output.
```
[2018-02-12 09:22:05,545] DEBUG Fetch READ_UNCOMMITTED at offset 15533 for partition foo-topic-10 returned fetch data (error=NONE, highWaterMark=15686, lastStableOffset = -1, logStartOffset = 0, abortedTransactions = null, recordsSizeInBytes=1048576) (org.apache.kafka.clients.consumer.internals.Fetcher:225)
[2018-02-12 09:22:05,545] DEBUG Sending READ_UNCOMMITTED fetch for partitions [connect-configs-0] to broker broker1.<broker_ip_redacted>:9092 (id: 7 rack: null) (org.apache.kafka.clients.consumer.internals.Fetcher:201)
[2018-02-12 09:22:05,549] DEBUG Added sensor with name topic.foo-topic.bytes-fetched (org.apache.kafka.common.metrics.Metrics:403)
[2018-02-12 09:22:05,550] DEBUG Added sensor with name topic.foo-topic.records-fetched (org.apache.kafka.common.metrics.Metrics:403)
[2018-02-12 09:22:05,550] DEBUG Added sensor with name foo-topic-10.records-lag (org.apache.kafka.common.metrics.Metrics:403)
[2018-02-12 09:22:05,550] DEBUG Added READ_UNCOMMITTED fetch request for partition foo-topic-10 at offset 15649 to node broker2.<broker_ip_redacted>:9092 (id: 8 rack: null) (org.apache.kafka.clients.consumer.internals.Fetcher:787)
[2018-02-12 09:22:05,550] DEBUG Sending READ_UNCOMMITTED fetch for partitions [foo-topic-10] to broker broker2.<broker_ip_redacted>:9092 (id: 8 rack: null) (org.apache.kafka.clients.consumer.internals.Fetcher:201)
[2018-02-12 09:22:05,551] WARN WorkerSinkTask{id=foo-topic-qa-2} Offset commit failed during close (org.apache.kafka.connect.runtime.WorkerSinkTask:324)
[2018-02-12 09:22:05,551] ERROR WorkerSinkTask{id=foo-topic-qa-2} Commit of offsets threw an unexpected exception for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask:215)
java.lang.NullPointerException
        at io.confluent.connect.s3.S3SinkTask.preCommit(S3SinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:513)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:154)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2018-02-12 09:22:05,552] ERROR Task foo-topic-qa-2 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:148)
java.lang.NullPointerException
        at io.confluent.connect.s3.S3SinkTask.close(S3SinkTask.java:206)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:339)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:513)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:154)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by mleveck** [comment]
@tomaszj @drewdahlke @ismail261 Try setting `timezone` in your connector config.  That seems to resolve the issue for me.  To the Confluent team perhaps document this setting as a dependency for `rotate.schedule.interval.ms` ?

**Comment by tomaszj** [comment]
Thanks for the tip @mleveck – I'll try that out sometime when I'll be looking again at the same piece.

**Comment by jocelyndrean** [comment]
I reproduced this error even with the `timezone` property set :(

**Comment by amanfredi** [comment]
Same for me with timezone set

**Comment by amanfredi** [comment]
I fixed it by setting both timezone and locale. This is undocumented

**Comment by nogwater** [comment]
I had this error and adding "timezone": "UTC" to my config fixed it for me.  Thanks!

**Comment by kgupta26** [comment]
> I had this error and adding "timezone": "UTC" to my config fixed it for me. Thanks!

same. thank you

**Comment by kgupta26** [comment]
> I had this error and adding "timezone": "UTC" to my config fixed it for me. Thanks!

same. thank you

**Comment by gharris1727** [comment]
For anyone still experiencing this error after setting the timezone, this is because the underlying timezone library being used doesn't support all of the timezones you might expect: https://www.joda.org/joda-time/apidocs/org/joda/time/DateTimeZone.html#forID-java.lang.String-

On my machine, the IDs supported by TimeZone but not DateTimeZone are: `JST, IST, BET, ACT, AET, Europe/Saratov, AGT, VST, SystemV/AST4, CNT, NET, SystemV/MST7, PLT, CST, SST, SystemV/CST6, CTT, PNT, BST, SystemV/YST9, MIT, ART, AST, America/Punta_Arenas, PRT, SystemV/HST10, PST, SystemV/EST5, IET, SystemV/PST8, SystemV/CST6CDT, NST, EAT, ECT, SystemV/MST7MDT, Asia/Atyrau, SystemV/YST9YDT, CAT, SystemV/PST8PDT, SystemV/AST4ADT, SystemV/EST5EDT`

If you have one of these timezones in your configuration, then you need to migrate to the nearest supported timezone, or an explicit offset like `[+/-]hh:mm`.

**Comment by gharris1727** [comment]
The NPE itself is fixed by #322 , but that just changes the exception from a NullPointerException to an IllegalArgumentException during runtime. Separately, validation for the timezone field will need to be added for when the `rotate.schedule.interval.ms` configuration is set.
