### ISSUE TITLE
Not compatible with Kafka 3.8 libraries

### ISSUE THREAD

**Issue by dpiddock** [confluentinc/kafka-connect-storage-cloud#781]
We tried upgrading our client libraries to Kafka 3.8 and started to get an exception:
```
Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:233)
java.lang.NoClassDefFoundError: Could not initialize class io.confluent.connect.s3.S3SinkConnectorConfig$CannedAclValidator
	at io.confluent.connect.s3.S3SinkConnectorConfig.newConfigDef(S3SinkConnectorConfig.java:467)
	at io.confluent.connect.s3.S3SinkConnectorConfig.<init>(S3SinkConnectorConfig.java:839)
	at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:100)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerTask.doStart(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'java.lang.String org.apache.kafka.common.utils.Utils.join(java.util.Collection, java.lang.String)' [in thread "task-thread-backup-events-to-s3-113"]
	at io.confluent.connect.s3.S3SinkConnectorConfig$CannedAclValidator.<clinit>(S3SinkConnectorConfig.java:1222)
	... 13 more
```

Kafka common.utils.Utils since 3.8.0 has removed the join method and replaced all uses with `String.join()` in https://github.com/apache/kafka/pull/15823

**Comment by dpiddock** [comment]
We have kept client libraries on Kafka 3.7.x.

**Comment by marcelstoer** [comment]
I ran into [an argument with the Kafka maintainers](https://github.com/apache/kafka/pull/15823#issuecomment-2508069034) over why they removed a public method (`Utils.join()`) in a minor release as it's a breaking change. Turns out they consider the whole `org.apache.kafka.common.utils` package "internal".

**Comment by juanAmayaRamirez** [comment]
this seems weird, I am using some connectors that suddenly broke due to this change...

**Comment by nitishkumar71** [comment]
For the time being which version from the release can be used?
