### ISSUE TITLE
Retry on AmazonS3Exception when uploading S3 files

### ISSUE THREAD

**Issue by zzbennett** [confluentinc/kafka-connect-storage-cloud#81]
Just encountered this exception from S3:

```
[2017-08-06 06:22:41,094] ERROR Multipart upload failed to complete for bucket 'xxx' key 'xxxxxxxxxxxxxx' (io.confluent.connect.s3.storage.S3OutputStream)
[2017-08-06 06:22:41,094] ERROR Task tracerbullet-2-S3-staging-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.kafka.connect.errors.DataException: Multipart upload failed to complete.
        at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:138)
        at com.stitchfix.datahighway.sfs3connector.SFCSVRecordWriterProvider$1.commit(SFCSVRecordWriterProvider.java:86)
        at io.confluent.connect.s3.TopicPartitionWriter.commitFile(TopicPartitionWriter.java:419)
        at io.confluent.connect.s3.TopicPartitionWriter.commitFiles(TopicPartitionWriter.java:399)
        at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:209)
        at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:173)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:429)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: null; Status Code: 0; Error Code: InternalError; Request ID: D923FC82C75E2B6E), S3 Extended Request ID: xsRu3H8odRxZiQi+n38Ah0yUiUp8pTWsc9FeVNTyCf8GxDMQYFPiu7vptFbmwznPsM+PY9O/fug=
        at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$CompleteMultipartUploadHandler.doEndElement(XmlResponsesSaxParser.java:1773)
        at com.amazonaws.services.s3.model.transform.AbstractHandler.endElement(AbstractHandler.java:52)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseXmlInputStream(XmlResponsesSaxParser.java:142)
        at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseCompleteMultipartUploadResponse(XmlResponsesSaxParser.java:462)
        at com.amazonaws.services.s3.model.transform.Unmarshallers$CompleteMultipartUploadResultUnmarshaller.unmarshall(Unmarshallers.java:230)
        at com.amazonaws.services.s3.model.transform.Unmarshallers$CompleteMultipartUploadResultUnmarshaller.unmarshall(Unmarshallers.java:227)
        at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
        at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:44)
        at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:30)
        at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1501)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1222)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4185)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4132)
        at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:2933)
        at io.confluent.connect.s3.storage.S3OutputStream$MultipartUpload.complete(S3OutputStream.java:206)
        at io.confluent.connect.s3.storage.S3OutputStream.commit(S3OutputStream.java:134)
        ... 16 more
[2017-08-06 06:22:41,094] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask)
```

Restarting the connector resolved it. Would be great if it could retry instead of crashing. Related to this issue as well: https://github.com/confluentinc/kafka-connect-storage-cloud/issues/50

**Comment by klamouri** [comment]
There is a pull request opened for this #78 

Let's hope it's going to be approved soon. It would be useful to a lot of people.

**Comment by kkonstantine** [comment]
Resolved by https://github.com/confluentinc/kafka-connect-storage-cloud/pull/78
